In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
concat_train=pd.concat([pd.read_csv('SDNFlow_Dataset_Normal.csv'), pd.read_csv('SDNFlow_Dataset_attack.csv')])

In [4]:
tester=pd.read_csv('modified_concatenated_InSDN_DatasetCSV.csv')

In [5]:
concat_train.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [6]:
tester.head()

,Flow ID,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,10/1/2020 5:02,269709,4,5,48,23,30,0,12.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,10/1/2020 5:02,268599,2,3,0,23,0,0,0.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,10/1/2020 5:02,22194,5,5,53,30,30,0,10.6,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,10/1/2020 1:39,9556,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,10/1/2020 1:39,8782,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [7]:
concat_train=concat_train.drop(columns=['eth_type','ipv4_src','ipv4_dst','src_port','dst_port'])

In [8]:
concat_train.head()

,flow_ID,ip_proto,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,Byts_max_interval_2s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,6,6.472,113472,628,17532.756490,97.033375,180.687898,12560,112694,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,6,6.465,24492,370,3788.399072,57.231245,66.194595,7400,24294,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,1,4.798,2211,4,460.817007,0.833681,552.750000,32,1180,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,17,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,44867,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,17,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,935885,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [9]:
concat_train=concat_train.drop(columns=['ip_proto'])

In [10]:
concat_train.head()

,flow_ID,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,Byts_max_interval_2s,Byts_min_interval_2s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,6.472,113472,628,17532.756490,97.033375,180.687898,12560,112694,0,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,6.465,24492,370,3788.399072,57.231245,66.194595,7400,24294,0,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,4.798,2211,4,460.817007,0.833681,552.750000,32,1180,0,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,44867,11454,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,935885,32828,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [11]:
tester.head()

,Flow ID,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,10/1/2020 5:02,269709,4,5,48,23,30,0,12.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,10/1/2020 5:02,268599,2,3,0,23,0,0,0.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,10/1/2020 5:02,22194,5,5,53,30,30,0,10.6,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,10/1/2020 1:39,9556,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,10/1/2020 1:39,8782,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [12]:
tester=tester.drop(columns=['Flow ID','Timestamp'])

In [13]:
nd=['flowduration','totallenpackets','totalpackets','flowbytes','flowpackets','packetsizeaverage','forwardheaderlength','activemax','activemin','activemean','activestd','idlemax','idlemin','idlemean','idlestd','target']

In [14]:
tester.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,30,0,12.0,14.696938,23,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,0,0,0.0,0.000000,23,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,30,0,10.6,14.724130,30,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,30,0,7.5,15.000000,30,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,30,0,7.5,15.000000,30,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [15]:
nd=pd.DataFrame(columns=['flowduration','totallenpackets','totalpackets','flowbytes','flowpackets','packetsizeaverage','forwardheaderlength','activemax','activemin','activemean','activestd','idlemax','idlemin','idlemean','idlestd','target'])

In [16]:
nd.head()

Empty DataFrame
Columns: [flowduration, totallenpackets, totalpackets, flowbytes, flowpackets, packetsizeaverage, forwardheaderlength, activemax, activemin, activemean, activestd, idlemax, idlemin, idlemean, idlestd, target]
Index: []

In [17]:
nd['flowduration']=concat_train['flow_duration']+tester['Flow Duration']

In [18]:
nd.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,forwardheaderlength,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,269715.472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,269718.173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,268605.465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,268608.173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22198.798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
s=pd.DataFrame(columns=['flowduration','totallenpackets','totalpackets','flowbytes','flowpackets','packetsizeaverage','forwardheaderlength','activemax','activemin','activemean','activestd','idlemax','idlemin','idlemean','idlestd','target'])

In [20]:
s.head()

Empty DataFrame
Columns: [flowduration, totallenpackets, totalpackets, flowbytes, flowpackets, packetsizeaverage, forwardheaderlength, activemax, activemin, activemean, activestd, idlemax, idlemin, idlemean, idlestd, target]
Index: []

In [21]:
s['totallenpackets']=tester['TotLen Fwd Pkts']+tester['TotLen Bwd Pkts']

In [22]:
s['totallenpackets']

0          71
1          23
2          83
3          60
4          60
         ...
343884      0
343885    646
343886    465
343887    259
343888    802
Name: totallenpackets, Length: 343889, dtype: int64

In [23]:
nd['totallenpackets']=concat_train['tot_len_pkts']+s['totallenpackets']

In [24]:
nd.head(100)

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,forwardheaderlength,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,269715.472,113543.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,269718.173,3431.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,268605.465,24515.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,268608.173,143.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22198.798,2294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,3461.198,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,9890.555,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,9890.197,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,4900.551,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,4900.190,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
s['totalpackets']=tester['Tot Fwd Pkts']+tester['Tot Bwd Pkts']

In [26]:
nd['totalpackets']=concat_train['tot_pkts']+s['totalpackets']

In [27]:
nd['flowbytes']=tester['Flow Byts/s']+concat_train['flow_byts_s']

In [28]:
nd['flowpackets']=tester['Fwd Pkts/s']+tester['Bwd Pkts/s']+concat_train['flow_pkts_s']

In [29]:
nd['packetsizeaverage']=tester['Pkt Size Avg']+concat_train['pkt_size_average']

In [30]:
nd['activemax']=tester['Active Max']+concat_train['active_max']

In [31]:
nd['activemin']=tester['Active Min']+concat_train['active_min']

In [32]:
nd['activemean']=tester['Active Mean']+concat_train['active_mean']

In [33]:
nd['activestd']=tester['Active Std']+concat_train['active_std']

In [34]:
nd['idlemax']=tester['Idle Max']+concat_train['idle_max']

In [35]:
nd['idlemean']=tester['Idle Mean']+concat_train['idle_mean']

In [36]:
nd['idlemin']=tester['Idle Min']+concat_train['idle_min']

In [37]:
nd['idlestd']=tester['Idle Std']+concat_train['idle_std']

In [38]:
nd.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,forwardheaderlength,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,269715.472,113543.0,637.0,17796.003174,130.402673,188.576787,NaN,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
0,269718.173,3431.0,65.0,629.539064,39.474171,67.888889,NaN,4.0,2.0,3.0,1.0,6.0,6.0,6.0,0.0,NaN
1,268605.465,24515.0,375.0,3874.028579,75.846355,70.794595,NaN,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
1,268608.173,143.0,7.0,98.711378,18.833141,64.600000,NaN,2.0,2.0,2.0,0.0,6.0,6.0,6.0,0.0,NaN
2,22198.798,2294.0,14.0,4200.566489,451.405908,561.050000,NaN,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,NaN

In [39]:
nd=nd.drop(columns=['forwardheaderlength'])

In [40]:
nd.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,269715.472,113543.0,637.0,17796.003174,130.402673,188.576787,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
0,269718.173,3431.0,65.0,629.539064,39.474171,67.888889,4.0,2.0,3.0,1.0,6.0,6.0,6.0,0.0,NaN
1,268605.465,24515.0,375.0,3874.028579,75.846355,70.794595,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
1,268608.173,143.0,7.0,98.711378,18.833141,64.600000,2.0,2.0,2.0,0.0,6.0,6.0,6.0,0.0,NaN
2,22198.798,2294.0,14.0,4200.566489,451.405908,561.050000,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,NaN

In [41]:
nd.shape

(662828, 15)

In [42]:
concat_train['Category'].value_counts()

Category
HTTP                 164974
probe                151456
dos                  123807
ddos                  74644
password-guessing     67288
DNS                   53551
sql_injection         17787
u2r                    6282
STREAMING              1487
SSH                    1133
ICMP                    305
FTP                      91
NTP                      23
Name: count, dtype: int64

In [43]:
tester['Label'].value_counts()

Label
Probe         98129
DDoS          73529
Normal        68424
DoS           53616
DDoS          48413
BFA            1405
Web-Attack      192
BOTNET          164
U2R              17
Name: count, dtype: int64

In [44]:
tester['Label']=tester['Label'].str.strip()

In [45]:
pd.set_option('display.max_columns', None)

In [46]:
tester.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,30,0,12.0,14.696938,23,0,4.600000,10.285913,263.246684,33.369298,33713.625000,90272.549880,257068,14,260808,86936.0,149854.765700,259973,104,269709,67427.250000,126912.740800,257785,2956,0,0,0,0,128,176,14.830799,18.538499,0,30,7.100000,11.779926,138.766667,0,1,0,0,0,0,0,0,1,7.888889,12.0,4.600000,0,0,0,0,0,0,4,48,5,23,-1,64,2,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,0,0,0.0,0.000000,23,0,7.666667,13.279056,85.629507,18.615110,67149.750000,132430.553600,265786,11,265811,265811.0,0.000000,265811,265811,268574,134287.000000,185983.225600,265797,2777,0,0,0,0,64,112,7.446044,11.169066,0,23,3.833333,9.389711,88.166667,0,1,0,0,0,0,0,0,1,4.600000,0.0,7.666667,0,0,0,0,0,0,2,0,3,23,-1,64,0,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,30,0,10.6,14.724130,30,0,6.000000,13.416408,3739.749482,450.572227,2466.000000,2951.053583,8063,3,17518,4379.5,6184.320254,13537,3,15128,3782.000000,3420.925898,8063,42,0,0,0,0,160,176,225.286113,225.286113,0,30,7.545455,13.048859,170.272727,0,1,0,0,0,0,0,0,1,8.300000,10.6,6.000000,0,0,0,0,0,0,5,53,5,30,-1,215,2,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,30,0,7.5,15.000000,30,0,7.500000,15.000000,6278.777731,837.170364,1365.142857,1447.714225,4022,13,5511,1837.0,1441.824885,3380,524,5588,1862.666667,2386.259067,4559,23,0,0,0,0,128,144,418.585182,418.585182,0,30,6.666667,13.228757,175.000000,0,1,0,0,0,0,0,0,1,7.500000,7.5,7.500000,0,0,0,0,0,0,4,30,4,30,-1,215,1,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,30,0,7.5,15.000000,30,0,7.500000,15.000000,6832.156684,910.954225,1254.571429,1607.096435,4049,8,4725,1575.0,2277.042160,4204,226,5618,1872.666667,2191.816674,4287,8,0,0,0,0,128,144,455.477112,455.477112,0,30,6.666667,13.228757,175.000000,0,1,0,0,0,0,0,0,1,7.500000,7.5,7.500000,0,0,0,0,0,0,4,30,4,30,-1,215,1,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [47]:
concat_train.head()

,flow_ID,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,Byts_max_interval_2s,Byts_min_interval_2s,Byts_mean_interval_2s,Byts_std_interval_2s,Pkts_max_interval_2s,Pkts_mean_interval_2s,Pkts_min_interval_2s,Pkts_std_interval_2s,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,6.472,113472,628,17532.756490,97.033375,180.687898,12560,112694,0,28368.00000,48686.674830,625,157.000000,0,270.202702,2,2.0,2,0.0,5,5.0,5,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,6.465,24492,370,3788.399072,57.231245,66.194595,7400,24294,0,6123.00000,10491.343150,367,92.500000,0,158.487381,2,2.0,2,0.0,5,5.0,5,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,4.798,2211,4,460.817007,0.833681,552.750000,32,1180,0,737.00000,524.675773,2,1.333333,0,0.942809,4,4.0,4,0.0,0,0.0,0,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,44867,11454,36334.95638,2870.840349,103,85.996644,22,4.407512,596,596.0,596,0.0,0,0.0,0,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,935885,32828,518629.67790,121204.950600,673,384.912752,29,84.666811,596,596.0,596,0.0,0,0.0,0,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [48]:
nd.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,269715.472,113543.0,637.0,17796.003174,130.402673,188.576787,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
0,269718.173,3431.0,65.0,629.539064,39.474171,67.888889,4.0,2.0,3.0,1.0,6.0,6.0,6.0,0.0,NaN
1,268605.465,24515.0,375.0,3874.028579,75.846355,70.794595,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,NaN
1,268608.173,143.0,7.0,98.711378,18.833141,64.600000,2.0,2.0,2.0,0.0,6.0,6.0,6.0,0.0,NaN
2,22198.798,2294.0,14.0,4200.566489,451.405908,561.050000,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,NaN

In [49]:
tester['Label'].value_counts()

Label
DDoS          121942
Probe          98129
Normal         68424
DoS            53616
BFA             1405
Web-Attack       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [50]:
concat_train['Category'].value_counts()

Category
HTTP                 164974
probe                151456
dos                  123807
ddos                  74644
password-guessing     67288
DNS                   53551
sql_injection         17787
u2r                    6282
STREAMING              1487
SSH                    1133
ICMP                    305
FTP                      91
NTP                      23
Name: count, dtype: int64

In [51]:
tester['Label']=tester['Label'].str.upper()

In [52]:
tester['Label'].value_counts()

Label
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [53]:
concat_train['Category']=concat_train['Category'].str.upper()

In [54]:
concat_train['Category'].value_counts()

Category
HTTP                 164974
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
STREAMING              1487
SSH                    1133
ICMP                    305
FTP                      91
NTP                      23
Name: count, dtype: int64

In [55]:
normal=['HTTP','SSH','ICMP','FTP','NTP']

In [56]:
concat_train['Category']=concat_train['Category'].replace({'HTTP':'NORMAL','SSH':'NORMAL','ICMP':'NORMAL','FTP':'NORMAL','NTP':'NORMAL'})

In [57]:
concat_train['Category'].value_counts()

Category
NORMAL               166526
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
STREAMING              1487
Name: count, dtype: int64

In [58]:
concat_train['Category']=concat_train['Category'].replace({'DNS':'BOTNET','STREAMING':'BOTNET'})

In [59]:
concat_train['Category'].value_counts()

Category
NORMAL               166526
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
BOTNET                55038
SQL_INJECTION         17787
U2R                    6282
Name: count, dtype: int64

In [60]:
tester['Label'].value_counts()

Label
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [61]:
concat_train['Category']=concat_train['Category'].replace({'PASSWORD-GUESSING':'BFA'})

In [62]:
concat_train['Category'].value_counts()

Category
NORMAL           166526
PROBE            151456
DOS              123807
DDOS              74644
BFA               67288
BOTNET            55038
SQL_INJECTION     17787
U2R                6282
Name: count, dtype: int64

In [63]:
concat_train['Category']=concat_train['Category'].replace({'SQL_INJECTION':'WEB-ATTACK'})

In [64]:
concat_train['Category'].value_counts()

Category
NORMAL        166526
PROBE         151456
DOS           123807
DDOS           74644
BFA            67288
BOTNET         55038
WEB-ATTACK     17787
U2R             6282
Name: count, dtype: int64

In [65]:
tester['Label'].value_counts()

Label
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [66]:
pd.set_option('display.max_rows', None)

In [67]:
concat_train.isnull().sum()

flow_ID                  0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Attack                   0
Category                 0
dtype: int64

In [68]:
concat_train=concat_train.replace([np.inf, -np.inf], np.nan, inplace=True)

In [69]:
concat_train.isnull().sum()

flow_ID                  0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Attack                   0
Category                 0
dtype: int64

In [70]:
concat_train=concat_train.fillna(0, inplace=True)

In [71]:
concat_train.isnull().sum()

flow_ID                  0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Attack                   0
Category                 0
dtype: int64

In [72]:
concat_train.head()

,flow_ID,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,Byts_max_interval_2s,Byts_min_interval_2s,Byts_mean_interval_2s,Byts_std_interval_2s,Pkts_max_interval_2s,Pkts_mean_interval_2s,Pkts_min_interval_2s,Pkts_std_interval_2s,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,6.472,113472,628,17532.756490,97.033375,180.687898,12560,112694,0,28368.00000,48686.674830,625,157.000000,0,270.202702,2,2.0,2,0.0,5,5.0,5,0.0,113472,7295988,628,6659,628,1,10,0,NORMAL
1,2,6.465,24492,370,3788.399072,57.231245,66.194595,7400,24294,0,6123.00000,10491.343150,367,92.500000,0,158.487381,2,2.0,2,0.0,5,5.0,5,0.0,26080,24492,381,370,370,2,1,0,NORMAL
2,3,4.798,2211,4,460.817007,0.833681,552.750000,32,1180,0,737.00000,524.675773,2,1.333333,0,0.942809,4,4.0,4,0.0,0,0.0,0,0.0,28291,3799,385,15,0,3,2,0,NORMAL
3,4,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,44867,11454,36334.95638,2870.840349,103,85.996644,22,4.407512,596,596.0,596,0.0,0,0.0,0,0.0,188960322,180776253,157117,153898,30743,60,19,0,BOTNET
4,5,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,935885,32828,518629.67790,121204.950600,673,384.912752,29,84.666811,596,596.0,596,0.0,0,0.0,0,0.0,188960322,180776253,157117,153898,122654,60,19,0,BOTNET

In [73]:
s.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,forwardheaderlength,activemax,activemin,activemean,activestd,idlemax,idlemin,idlemean,idlestd,target
0,NaN,71,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,23,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,83,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,60,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,60,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
concat_train=concat_train.drop(columns=['flow_ID','Byts_max_interval_2s','Byts_min_interval_2s','Byts_mean_interval_2s','Byts_std_interval_2s','Pkts_max_interval_2s','Pkts_mean_interval_2s','Pkts_min_interval_2s','Pkts_std_interval_2s','TnBPDstIP','TnBPSrcIP','TnPPDstIP','TnPPSrcIP','TnPPerDport','Tn_FlowsPDstIP','Tn_FlowsPSrcIP'])

In [75]:
concat_train.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Attack,Category
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [76]:
concat_train['Attack'].value_counts()

Attack
1    441264
0    221564
Name: count, dtype: int64

In [77]:
concat_train=concat_train.rename(columns={'flow_duration':'flowduration','tot_len_pkts':'totallenpackets','tot_pkts':'totalpackets','flow_byts_s':'flowbytes','flow_pkts_s':'flowpackets','pkt_size_average':'packetsizeaverage','active_max':'activemax','active_min':'activemin','active_mean':'activemean','active_std':'activestd','idle_max':'idlemax','idle_min':'idlemin','idle_mean':'idlemean','idle_std':'idlestd','Category':'target'})

In [78]:
concat_train.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,Attack,target
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [79]:
tester.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,30,0,12.0,14.696938,23,0,4.600000,10.285913,263.246684,33.369298,33713.625000,90272.549880,257068,14,260808,86936.0,149854.765700,259973,104,269709,67427.250000,126912.740800,257785,2956,0,0,0,0,128,176,14.830799,18.538499,0,30,7.100000,11.779926,138.766667,0,1,0,0,0,0,0,0,1,7.888889,12.0,4.600000,0,0,0,0,0,0,4,48,5,23,-1,64,2,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,0,0,0.0,0.000000,23,0,7.666667,13.279056,85.629507,18.615110,67149.750000,132430.553600,265786,11,265811,265811.0,0.000000,265811,265811,268574,134287.000000,185983.225600,265797,2777,0,0,0,0,64,112,7.446044,11.169066,0,23,3.833333,9.389711,88.166667,0,1,0,0,0,0,0,0,1,4.600000,0.0,7.666667,0,0,0,0,0,0,2,0,3,23,-1,64,0,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,30,0,10.6,14.724130,30,0,6.000000,13.416408,3739.749482,450.572227,2466.000000,2951.053583,8063,3,17518,4379.5,6184.320254,13537,3,15128,3782.000000,3420.925898,8063,42,0,0,0,0,160,176,225.286113,225.286113,0,30,7.545455,13.048859,170.272727,0,1,0,0,0,0,0,0,1,8.300000,10.6,6.000000,0,0,0,0,0,0,5,53,5,30,-1,215,2,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,30,0,7.5,15.000000,30,0,7.500000,15.000000,6278.777731,837.170364,1365.142857,1447.714225,4022,13,5511,1837.0,1441.824885,3380,524,5588,1862.666667,2386.259067,4559,23,0,0,0,0,128,144,418.585182,418.585182,0,30,6.666667,13.228757,175.000000,0,1,0,0,0,0,0,0,1,7.500000,7.5,7.500000,0,0,0,0,0,0,4,30,4,30,-1,215,1,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,30,0,7.5,15.000000,30,0,7.500000,15.000000,6832.156684,910.954225,1254.571429,1607.096435,4049,8,4725,1575.0,2277.042160,4204,226,5618,1872.666667,2191.816674,4287,8,0,0,0,0,128,144,455.477112,455.477112,0,30,6.666667,13.228757,175.000000,0,1,0,0,0,0,0,0,1,7.500000,7.5,7.500000,0,0,0,0,0,0,4,30,4,30,-1,215,1,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [80]:
tester=tester.drop(columns=['Fwd Pkt Len Max','Fwd Pkt Len Min','Fwd Pkt Len Mean','Fwd Pkt Len Std','Bwd Pkt Len Max','Bwd Pkt Len Min','Bwd Pkt Len Mean','Bwd Pkt Len Std','Flow IAT Mean','Flow IAT Std','Flow IAT Max','Flow IAT Min','Fwd IAT Tot','Fwd IAT Mean','Fwd IAT Std','Fwd IAT Max','Fwd IAT Min','Bwd IAT Tot','Bwd IAT Mean','Bwd IAT Std','Bwd IAT Max','Bwd IAT Min','Fwd PSH Flags','Bwd PSH Flags','Fwd URG Flags','Bwd URG Flags','Pkt Len Min','Pkt Len Max','Pkt Len Mean','Pkt Len Std','Pkt Len Var','FIN Flag Cnt','SYN Flag Cnt','RST Flag Cnt','PSH Flag Cnt','ACK Flag Cnt','URG Flag Cnt','CWE Flag Count','ECE Flag Cnt','Down/Up Ratio','Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min'])

In [81]:
tester.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Flow Byts/s,Flow Pkts/s,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Size Avg,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,263.246684,33.369298,128,176,14.830799,18.538499,7.888889,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,85.629507,18.615110,64,112,7.446044,11.169066,4.600000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,3739.749482,450.572227,160,176,225.286113,225.286113,8.300000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,6278.777731,837.170364,128,144,418.585182,418.585182,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,6832.156684,910.954225,128,144,455.477112,455.477112,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [82]:
tester['Tot Fwd Pkts']=tester['Tot Fwd Pkts']+tester['Tot Bwd Pkts']

In [83]:
tester=tester.drop(columns=['Tot Bwd Pkts'])

In [84]:
tester.head()

,Flow Duration,Tot Fwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Flow Byts/s,Flow Pkts/s,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Size Avg,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,9,48,23,263.246684,33.369298,128,176,14.830799,18.538499,7.888889,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,5,0,23,85.629507,18.615110,64,112,7.446044,11.169066,4.600000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,10,53,30,3739.749482,450.572227,160,176,225.286113,225.286113,8.300000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,8,30,30,6278.777731,837.170364,128,144,418.585182,418.585182,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,8,30,30,6832.156684,910.954225,128,144,455.477112,455.477112,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [85]:
tester=tester.drop(columns=['TotLen Bwd Pkts', 'TotLen Fwd Pkts'])

In [86]:
tester.head()

,Flow Duration,Tot Fwd Pkts,Flow Byts/s,Flow Pkts/s,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Size Avg,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,9,263.246684,33.369298,128,176,14.830799,18.538499,7.888889,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,5,85.629507,18.615110,64,112,7.446044,11.169066,4.600000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,10,3739.749482,450.572227,160,176,225.286113,225.286113,8.300000,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,8,6278.777731,837.170364,128,144,418.585182,418.585182,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,8,6832.156684,910.954225,128,144,455.477112,455.477112,7.500000,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [87]:
concat_train.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,Attack,target
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [88]:
tester['Tot Fwd Pkts']=tester['Tot Fwd Pkts'].rename('totalpackets')

In [89]:
tester.isnull().sum()

Flow Duration     0
Tot Fwd Pkts      0
Flow Byts/s       0
Flow Pkts/s       0
Fwd Header Len    0
Bwd Header Len    0
Fwd Pkts/s        0
Bwd Pkts/s        0
Pkt Size Avg      0
Active Mean       0
Active Std        0
Active Max        0
Active Min        0
Idle Mean         0
Idle Std          0
Idle Max          0
Idle Min          0
Label             0
dtype: int64

In [90]:
tester=tester.drop(columns=['Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Size Avg'])

In [91]:
tester.isnull().sum()

Flow Duration     0
Tot Fwd Pkts      0
Flow Byts/s       0
Flow Pkts/s       0
Fwd Header Len    0
Active Mean       0
Active Std        0
Active Max        0
Active Min        0
Idle Mean         0
Idle Std          0
Idle Max          0
Idle Min          0
Label             0
dtype: int64

In [92]:
concat_train.isnull().sum()

flowduration         0
totallenpackets      0
totalpackets         0
flowbytes            0
flowpackets          0
packetsizeaverage    0
fwd_header_len       0
activemax            0
activemean           0
activemin            0
activestd            0
idlemax              0
idlemean             0
idlemin              0
idlestd              0
Attack               0
target               0
dtype: int64

In [93]:
tester=tester.rename(columns={'Tot Fwd Pkts':'totalpackets','Flow Duration':'flowduration','Flow Byts/s':'flowbytes','Flow Pkts/s':'flowpackets','Fwd Header Len':'fwd_header_len','Active Mean':'activemean','Active Max':'activemax','Active Min':'activemin','Active Std':'activestd','Idle Std':'idlestd','Idle min':'idlemin','Idle mean':'idlemean','Idle Max':'idlemax'})

In [94]:
tester.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemean,activestd,activemax,activemin,Idle Mean,idlestd,idlemax,Idle Min,Label
0,269709,9,263.246684,33.369298,128,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,5,85.629507,18.615110,64,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,10,3739.749482,450.572227,160,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,8,6278.777731,837.170364,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,8,6832.156684,910.954225,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [95]:
concat_train.head()

,flowduration,totallenpackets,totalpackets,flowbytes,flowpackets,packetsizeaverage,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,Attack,target
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [96]:
concat_train=concat_train.drop(columns=['totallenpackets','packetsizeaverage'])

In [97]:
concat_train.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,Attack,target
0,6.472,628,17532.756490,97.033375,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,370,3788.399072,57.231245,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,4,460.817007,0.833681,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,25627,18189.757590,43.051052,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,114704,259641.132900,192.698542,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [98]:
tester.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemean,activestd,activemax,activemin,Idle Mean,idlestd,idlemax,Idle Min,Label
0,269709,9,263.246684,33.369298,128,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,5,85.629507,18.615110,64,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,10,3739.749482,450.572227,160,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,8,6278.777731,837.170364,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,8,6832.156684,910.954225,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [99]:
tester=tester.rename(columns={'Label':'target','Idle Mean':'idlemean','Idle Min':'idlemin'})

In [100]:
tester.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemean,activestd,activemax,activemin,idlemean,idlestd,idlemax,idlemin,target
0,269709,9,263.246684,33.369298,128,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,5,85.629507,18.615110,64,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,10,3739.749482,450.572227,160,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,8,6278.777731,837.170364,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,8,6832.156684,910.954225,128,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [101]:
concat_train.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,Attack,target
0,6.472,628,17532.756490,97.033375,12560,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
1,6.465,370,3788.399072,57.231245,7400,2,2.0,2,0.0,5,5.0,5,0.0,0,NORMAL
2,4.798,4,460.817007,0.833681,32,4,4.0,4,0.0,0,0.0,0,0.0,0,NORMAL
3,595.270,25627,18189.757590,43.051052,205016,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET
4,595.251,114704,259641.132900,192.698542,917632,596,596.0,596,0.0,0,0.0,0,0.0,0,BOTNET

In [102]:
concat_train=concat_train.drop(columns=['Attack'])

In [103]:
concat_train.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,target
0,6.472,628,17532.756490,97.033375,12560,2,2.0,2,0.0,5,5.0,5,0.0,NORMAL
1,6.465,370,3788.399072,57.231245,7400,2,2.0,2,0.0,5,5.0,5,0.0,NORMAL
2,4.798,4,460.817007,0.833681,32,4,4.0,4,0.0,0,0.0,0,0.0,NORMAL
3,595.270,25627,18189.757590,43.051052,205016,596,596.0,596,0.0,0,0.0,0,0.0,BOTNET
4,595.251,114704,259641.132900,192.698542,917632,596,596.0,596,0.0,0,0.0,0,0.0,BOTNET

In [104]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [105]:
from sklearn.preprocessing import LabelEncoder

In [106]:
labelencoder=LabelEncoder()

In [107]:
concat_train['target']=labelencoder.fit_transform(concat_train['target'])

In [108]:
concat_train.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd,target
0,6.472,628,17532.756490,97.033375,12560,2,2.0,2,0.0,5,5.0,5,0.0,4
1,6.465,370,3788.399072,57.231245,7400,2,2.0,2,0.0,5,5.0,5,0.0,4
2,4.798,4,460.817007,0.833681,32,4,4.0,4,0.0,0,0.0,0,0.0,4
3,595.270,25627,18189.757590,43.051052,205016,596,596.0,596,0.0,0,0.0,0,0.0,1
4,595.251,114704,259641.132900,192.698542,917632,596,596.0,596,0.0,0,0.0,0,0.0,1

In [109]:
Y=concat_train['target']

In [110]:
X= concat_train.drop(columns=['target'])

In [111]:
X.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemax,activemean,activemin,activestd,idlemax,idlemean,idlemin,idlestd
0,6.472,628,17532.756490,97.033375,12560,2,2.0,2,0.0,5,5.0,5,0.0
1,6.465,370,3788.399072,57.231245,7400,2,2.0,2,0.0,5,5.0,5,0.0
2,4.798,4,460.817007,0.833681,32,4,4.0,4,0.0,0,0.0,0,0.0
3,595.270,25627,18189.757590,43.051052,205016,596,596.0,596,0.0,0,0.0,0,0.0
4,595.251,114704,259641.132900,192.698542,917632,596,596.0,596,0.0,0,0.0,0,0.0

In [112]:
Y.head()

0    4
1    4
2    4
3    1
4    1
Name: target, dtype: int64

In [113]:
Y.value_counts()

target
4    166526
5    151456
3    123807
2     74644
0     67288
1     55038
7     17787
6      6282
Name: count, dtype: int64

In [114]:
pip install imblearn

Requirement already satisfied: imblearn in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from imblearn) (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from imbalanced-learn->imblearn) (2.4.2)
Requirement already satisfied: scipy<2,>=1.11.4 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from imbalanced-learn->imblearn) (1.17.0)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from imbalanced-learn->imblearn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from imbalanced-learn->imblearn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [115]:
from imblearn.over_sampling import SMOTE

In [116]:
smote=SMOTE()

In [117]:
Xr,Yr=smote.fit_resample(X,Y)

In [118]:
Yr.value_counts()

target
4    166526
1    166526
2    166526
3    166526
5    166526
7    166526
0    166526
6    166526
Name: count, dtype: int64

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [121]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [122]:
Xr,Yr=smote.fit_resample(X_train,Y_train)

In [123]:
Yr.value_counts()

target
2    133433
5    133433
3    133433
1    133433
0    133433
4    133433
7    133433
6    133433
Name: count, dtype: int64

In [124]:
Xr

array([[-0.18274953, -0.00794589, -0.01768163, ..., -0.39298997,
        -0.38147868, -0.18969474],
       [-0.20732704, -0.00794589, -0.01768163, ..., -0.39298997,
        -0.38147868, -0.18969474],
       [-0.20053208, -0.0072433 , -0.0151194 , ..., -0.39298997,
        -0.38147868, -0.18969474],
       ...,
       [-0.17280176, -0.0070091 , -0.01373093, ..., -0.39298997,
        -0.38147868, -0.18969474],
       [-0.20450785, -0.0072433 ,  0.05269033, ..., -0.39298997,
        -0.38147868, -0.18969474],
       [ 0.13506217, -0.0070091 , -0.01489882, ...,  1.18605256,
         1.32230213, -0.18969474]], shape=(1067464, 13))

In [125]:
pip install scikit-optimize

Requirement already satisfied: scikit-optimize in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (0.10.2)
Requirement already satisfied: joblib>=0.11 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-optimize) (1.5.3)
Requirement already satisfied: pyaml>=16.9 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-optimize) (26.2.1)
Requirement already satisfied: numpy>=1.20.3 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from scikit-optimize) (2.4.2)
Requirement already satisfied: scipy>=1.1.0 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from scikit-optimize) (1.17.0)
Requirement already satisfied: scikit-learn>=1.0.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-optimize) (1.8.0)
Requirement already satisfied: packaging>=21.3 in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from scikit-optimize) (25.0)
Requirement already satisfied: PyYAML in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from pyaml>=16.9->scikit-optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [126]:
pip install xgboost

Requirement already satisfied: xgboost in c:\Users\quant\miniconda3\envs\quant\Lib\site-packages (3.2.0)
Requirement already satisfied: numpy in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in C:\Users\quant\AppData\Roaming\Python\Python314\site-packages (from xgboost) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [127]:
from xgboost import XGBClassifier
     

xgb=XGBClassifier()
     

estimators=[('xgb',xgb)]
     

from sklearn.pipeline import Pipeline
     

pipe=Pipeline(steps=estimators)
     

pipe

Pipeline(steps=[('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [128]:
from skopt import BayesSearchCV
     

from skopt.space import Real,Categorical,Integer
     

search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [129]:
opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=3,scoring='roc_auc',random_state=8)
     

opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=3
)

In [130]:
opt.fit(Xr,Yr)

BayesSearchCV(cv=3,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [133]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [134]:
Xpr=opt.predict(Xr)

In [135]:
accuracy_score(Yr,Xpr)

0.6642425412004527

In [136]:
classification_report(Yr,Xpr)

'              precision    recall  f1-score   support\n\n           0       0.82      0.72      0.76    133433\n           1       0.79      0.41      0.54    133433\n           2       0.92      0.28      0.43    133433\n           3       0.89      0.84      0.86    133433\n           4       0.77      0.55      0.64    133433\n           5       0.33      0.93      0.49    133433\n           6       0.87      0.83      0.85    133433\n           7       0.87      0.77      0.81    133433\n\n    accuracy                           0.66   1067464\n   macro avg       0.78      0.66      0.67   1067464\nweighted avg       0.78      0.66      0.67   1067464\n'

In [137]:
confusion_matrix(Yr,Xpr)

array([[ 95463,    902,    174,   1128,   5828,  21123,   2585,   6230],
       [   536,  55250,    373,    452,    746,  75234,    242,    600],
       [   140,   3210,  36992,    134,    622,  91850,    344,    141],
       [  3514,    307,    616, 111914,   7139,   5401,   2066,   2476],
       [  7088,   5672,    982,   8235,  73275,  30930,   5969,   1282],
       [   377,   3445,    973,   1098,   2540, 123605,   1252,    143],
       [  3892,    657,    154,    923,   2361,  10737, 110442,   4267],
       [  5993,    392,     36,   1881,   2550,  16767,   3700, 102114]])

In [140]:
tester=tester.replace([np.inf, -np.inf], np.nan, inplace=True)

In [141]:
tester.isnull().sum()

flowduration      0
totalpackets      0
flowbytes         0
flowpackets       0
fwd_header_len    0
activemean        0
activestd         0
activemax         0
activemin         0
idlemean          0
idlestd           0
idlemax           0
idlemin           0
target            0
dtype: int64

In [142]:
tester['target'].value_counts()

target
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [151]:
tester['target']=labelencoder.fit_transform(tester['target'])

In [152]:
tester.head()

,flowduration,totalpackets,flowbytes,flowpackets,fwd_header_len,activemean,activestd,activemax,activemin,idlemean,idlestd,idlemax,idlemin,target
0,269709,9,263.246684,33.369298,128,0.0,0.0,0,0,0.0,0.0,0,0,6
1,268599,5,85.629507,18.615110,64,0.0,0.0,0,0,0.0,0.0,0,0,6
2,22194,10,3739.749482,450.572227,160,0.0,0.0,0,0,0.0,0.0,0,0,6
3,9556,8,6278.777731,837.170364,128,0.0,0.0,0,0,0.0,0.0,0,0,0
4,8782,8,6832.156684,910.954225,128,0.0,0.0,0,0,0.0,0.0,0,0,0

In [153]:
Y1= tester['target']

In [154]:
X1=tester.drop(columns=['target'])

In [155]:
X1_train,X1_test,Y1_train,Y1_test=train_test_split(X1,Y1,test_size=0.2,random_state=2)

In [156]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X1_train = scaler.fit_transform(X1_train)

X1_test = scaler.transform(X1_test)

In [157]:
X1r,Y1r=smote.fit_resample(X1_train,Y1_train)

In [158]:
from xgboost import XGBClassifier
     

xgb=XGBClassifier()
     

estimators=[('xgb',xgb)]
     

from sklearn.pipeline import Pipeline
     

pipe=Pipeline(steps=estimators)
     

pipe

Pipeline(steps=[('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [159]:
from skopt import BayesSearchCV
     

from skopt.space import Real,Categorical,Integer
     

search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [160]:
opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=3,scoring='roc_auc',random_state=8)
     

opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=3
)

In [162]:
opt.fit(X1r,Y1r)

BayesSearchCV(cv=3,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [163]:
X1pr=opt.predict(X1_test)

In [171]:
accuracy_score(Y1_test,X1pr)

0.9517723690715054

In [172]:
classification_report(Y1_test,opt.predict(X1_test))

'              precision    recall  f1-score   support\n\n           0       0.22      0.69      0.34       254\n           1       0.70      0.97      0.81        36\n           2       0.94      0.99      0.96     24399\n           3       1.00      0.99      0.99     10770\n           4       0.99      0.97      0.98     13706\n           5       0.97      0.88      0.92     19566\n           6       0.50      0.67      0.57         3\n           7       0.12      0.86      0.22        44\n\n    accuracy                           0.95     68778\n   macro avg       0.68      0.88      0.72     68778\nweighted avg       0.96      0.95      0.96     68778\n'

In [173]:
confusion_matrix(Y1_test,X1pr)

array([[  175,     0,     0,     7,     1,    31,     0,    40],
       [    0,    35,     0,     0,     0,     1,     0,     0],
       [    0,     0, 24073,     1,     7,   262,     0,    56],
       [   41,    14,     0, 10644,    55,    12,     1,     3],
       [    0,     1,     4,    18, 13349,   307,     1,    26],
       [  562,     0,  1557,    16,   140, 17145,     0,   146],
       [    0,     0,     0,     1,     0,     0,     2,     0],
       [    6,     0,     0,     0,     0,     0,     0,    38]])