<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
d=pd.read_csv("SDNFlow_Dataset_Normal.csv")

In [25]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6.0,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6.0,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1.0,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,STREAMING

In [26]:
d.shape

(37248, 39)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
standardscaler=StandardScaler()

In [30]:
d.std

<bound method DataFrame.std of        flow_ID  eth_type        ipv4_src        ipv4_dst  ip_proto  src_port  \
0            1      2048  192.168.56.201    192.168.56.1       6.0      22.0
1            2      2048    192.168.56.1  192.168.56.201       6.0   41410.0
2            3      2048  192.168.56.203  192.168.56.201       1.0       0.0
3            4      2048  192.168.56.201  192.168.56.203      17.0   57426.0
4            5      2048  192.168.56.201  192.168.56.203      17.0   48549.0
...        ...       ...             ...             ...       ...       ...
37243    37244      2048  192.168.56.203   3.234.116.116       6.0   39190.0
37244    37245      2048  169.48.138.204  192.168.56.203       6.0     443.0
37245    37246      2048   54.164.210.99  192.168.56.203       6.0     443.0
37246    37247      2048   34.200.65.202  192.168.56.203       6.0     443.0
37247    37248      2048             NaN             NaN       NaN       NaN

       dst_port  flow_duration  tot_len_pkts  tot_pkts  ...  idle_std  \
0       41410.0          6.472      113472.0     628.0  ...       0.0
1          22.0          6.465       24492.0     370.0  ...       0.0
2           0.0          4.798        2211.0       4.0  ...       0.0
3        1236.0        595.270    10827817.0   25627.0  ...       0.0
4        1234.0        595.251   154551644.0  114704.0  ...       0.0
...         ...            ...           ...       ...  ...       ...
37243     443.0          8.443        1726.0      13.0  ...       0.0
37244   44050.0          0.436           0.0       0.0  ...       0.0
37245   49426.0          8.430        6205.0       8.0  ...       0.0
37246   49536.0          8.427        5656.0      13.0  ...       0.0
37247       NaN            NaN           NaN       NaN  ...       NaN

         TnBPDstIP    TnBPSrcIP  TnPPDstIP  TnPPSrcIP  TnPPerDport  \
0         113472.0    7295988.0      628.0     6659.0        628.0
1          26080.0      24492.0      381.0      370.0        370.0
2          28291.0       3799.0      385.0       15.0          0.0
3      188960322.0  180776253.0   157117.0   153898.0      30743.0
4      188960322.0  180776253.0   157117.0   153898.0     122654.0
...            ...          ...        ...        ...          ...
37243       1726.0     614435.0       13.0     3257.0       3168.0
37244  259156585.0          0.0   219780.0        0.0          0.0
37245  263216991.0      13841.0   223460.0       15.0          8.0
37246  263216991.0      14354.0   223460.0       30.0         13.0
37247          NaN          NaN        NaN        NaN          NaN

       Tn_FlowsPDstIP  Tn_FlowsPSrcIP  Attack   Category
0                 1.0            10.0     0.0        SSH
1                 2.0             1.0     0.0        SSH
2                 3.0             2.0     0.0       ICMP
3                60.0            19.0     0.0  STREAMING
4                60.0            19.0     0.0  STREAMING
...               ...             ...     ...        ...
37243             1.0           210.0     0.0       HTTP
37244           183.0             1.0     0.0       HTTP
37245           162.0             2.0     0.0       HTTP
37246           162.0             2.0     0.0       HTTP
37247             NaN             NaN     NaN        NaN

[37248 rows x 39 columns]>

In [31]:
print(d.std)

<bound method DataFrame.std of        flow_ID  eth_type        ipv4_src        ipv4_dst  ip_proto  src_port  \
0            1      2048  192.168.56.201    192.168.56.1       6.0      22.0
1            2      2048    192.168.56.1  192.168.56.201       6.0   41410.0
2            3      2048  192.168.56.203  192.168.56.201       1.0       0.0
3            4      2048  192.168.56.201  192.168.56.203      17.0   57426.0
4            5      2048  192.168.56.201  192.168.56.203      17.0   48549.0
...        ...       ...             ...             ...       ...       ...
37243    37244      2048  192.168.56.203   3.234.116.116       6.0   39190.0
37244    37245      2048  169.48.138.204  192.168.56.203       6.0     443.0
37245    37246      2048   54.164.210.99  192.168.56.203       6.0     443.0
37246    37247      2048   34.200.65.202  192.168.56.203       6.0     443.0
37247    37248      2048             NaN             NaN       NaN       NaN

       dst_port  flow_duration  tot_len_pkts  tot_pkts  ...  idle_std  \
0       41410.0          6.472      113472.0     628.0  ...       0.0
1          22.0          6.465       24492.0     370.0  ...       0.0
2           0.0          4.798        2211.0       4.0  ...       0.0
3        1236.0        595.270    10827817.0   25627.0  ...       0.0
4        1234.0        595.251   154551644.0  114704.0  ...       0.0
...         ...            ...           ...       ...  ...       ...
37243     443.0          8.443        1726.0      13.0  ...       0.0
37244   44050.0          0.436           0.0       0.0  ...       0.0
37245   49426.0          8.430        6205.0       8.0  ...       0.0
37246   49536.0          8.427        5656.0      13.0  ...       0.0
37247       NaN            NaN           NaN       NaN  ...       NaN

         TnBPDstIP    TnBPSrcIP  TnPPDstIP  TnPPSrcIP  TnPPerDport  \
0         113472.0    7295988.0      628.0     6659.0        628.0
1          26080.0      24492.0      381.0      370.0        370.0
2          28291.0       3799.0      385.0       15.0          0.0
3      188960322.0  180776253.0   157117.0   153898.0      30743.0
4      188960322.0  180776253.0   157117.0   153898.0     122654.0
...            ...          ...        ...        ...          ...
37243       1726.0     614435.0       13.0     3257.0       3168.0
37244  259156585.0          0.0   219780.0        0.0          0.0
37245  263216991.0      13841.0   223460.0       15.0          8.0
37246  263216991.0      14354.0   223460.0       30.0         13.0
37247          NaN          NaN        NaN        NaN          NaN

       Tn_FlowsPDstIP  Tn_FlowsPSrcIP  Attack   Category
0                 1.0            10.0     0.0        SSH
1                 2.0             1.0     0.0        SSH
2                 3.0             2.0     0.0       ICMP
3                60.0            19.0     0.0  STREAMING
4                60.0            19.0     0.0  STREAMING
...               ...             ...     ...        ...
37243             1.0           210.0     0.0       HTTP
37244           183.0             1.0     0.0       HTTP
37245           162.0             2.0     0.0       HTTP
37246           162.0             2.0     0.0       HTTP
37247             NaN             NaN     NaN        NaN

[37248 rows x 39 columns]>

In [32]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ipv4_src                 1
ipv4_dst                 1
ip_proto                 1
src_port                 1
dst_port                 1
flow_duration            1
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     1
active_max               1
active_mean              1
active_min               1
active_std               1
idle_max                 1
idle_mean                1
idle_min                 1
idle_std                 1
TnBPDstIP                1
TnBPSrcIP                1
TnPPDstIP                1
TnPPSrcIP                1
TnPPerDport              1
Tn_FlowsPDstIP           1
Tn_FlowsPSrcIP           1
Attack                   1
Category                 1
dtype: int64

In [33]:
d.tail()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
37243,37244,2048,192.168.56.203,3.234.116.116,6.0,39190.0,443.0,8.443,1726.0,13.0,...,0.0,1726.0,614435.0,13.0,3257.0,3168.0,1.0,210.0,0.0,HTTP
37244,37245,2048,169.48.138.204,192.168.56.203,6.0,443.0,44050.0,0.436,0.0,0.0,...,0.0,259156585.0,0.0,219780.0,0.0,0.0,183.0,1.0,0.0,HTTP
37245,37246,2048,54.164.210.99,192.168.56.203,6.0,443.0,49426.0,8.430,6205.0,8.0,...,0.0,263216991.0,13841.0,223460.0,15.0,8.0,162.0,2.0,0.0,HTTP
37246,37247,2048,34.200.65.202,192.168.56.203,6.0,443.0,49536.0,8.427,5656.0,13.0,...,0.0,263216991.0,14354.0,223460.0,30.0,13.0,162.0,2.0,0.0,HTTP
37247,37248,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
d=d.drop('Category',axis=1)

In [35]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_min,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack
0,1,2048,192.168.56.201,192.168.56.1,6.0,22.0,41410.0,6.472,113472.0,628.0,...,5.0,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0
1,2,2048,192.168.56.1,192.168.56.201,6.0,41410.0,22.0,6.465,24492.0,370.0,...,5.0,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0
2,3,2048,192.168.56.203,192.168.56.201,1.0,0.0,0.0,4.798,2211.0,4.0,...,0.0,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0
3,4,2048,192.168.56.201,192.168.56.203,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0
4,5,2048,192.168.56.201,192.168.56.203,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37243,37244,2048,192.168.56.203,3.234.116.116,6.0,39190.0,443.0,8.443,1726.0,13.0,...,5.0,0.0,1726.0,614435.0,13.0,3257.0,3168.0,1.0,210.0,0.0
37244,37245,2048,169.48.138.204,192.168.56.203,6.0,443.0,44050.0,0.436,0.0,0.0,...,0.0,0.0,259156585.0,0.0,219780.0,0.0,0.0,183.0,1.0,0.0
37245,37246,2048,54.164.210.99,192.168.56.203,6.0,443.0,49426.0,8.430,6205.0,8.0,...,5.0,0.0,263216991.0,13841.0,223460.0,15.0,8.0,162.0,2.0,0.0
37246,37247,2048,34.200.65.202,192.168.56.203,6.0,443.0,49536.0,8.427,5656.0,13.0,...,6.0,0.0,263216991.0,14354.0,223460.0,30.0,13.0,162.0,2.0,0.0
37247,37248,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
labelencoder=LabelEncoder()

In [38]:
labels=labelencoder.fit_transform(d.Attack)

In [39]:
labels

array([0, 0, 0, ..., 0, 0, 1])

In [40]:
print(labels)

[0 0 0 ... 0 0 1]

In [41]:
d['target']=labels

In [42]:
d['target'].value_counts()

target
0    37247
1        1
Name: count, dtype: int64

In [43]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,target
0,1,2048,192.168.56.201,192.168.56.1,6.0,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,0
1,2,2048,192.168.56.1,192.168.56.201,6.0,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,0
2,3,2048,192.168.56.203,192.168.56.201,1.0,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,0
3,4,2048,192.168.56.201,192.168.56.203,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,0
4,5,2048,192.168.56.201,192.168.56.203,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,0

In [44]:
drop_cols=['flow_ID','ipv4_src','ipv4_dst']

In [45]:
drop_cols

['flow_ID', 'ipv4_src', 'ipv4_dst']

In [46]:
d=d.drop(drop_cols,axis=1)

In [47]:
d.head()

,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,target
0,2048,6.0,22.0,41410.0,6.472,113472.0,628.0,17532.756490,97.033375,180.687898,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,0
1,2048,6.0,41410.0,22.0,6.465,24492.0,370.0,3788.399072,57.231245,66.194595,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,0
2,2048,1.0,0.0,0.0,4.798,2211.0,4.0,460.817007,0.833681,552.750000,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,0
3,2048,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,18189.757590,43.051052,422.515979,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,0
4,2048,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,259641.132900,192.698542,1347.395418,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,0

In [48]:
scaler=StandardScaler()

In [49]:
Xscaled=scaler.fit_transform(d)

In [50]:
Xscaled

array([[ 0.00000000e+00, -5.54668245e-01, -9.88628487e-01, ...,
        -8.37629696e-01,  0.00000000e+00, -5.18148626e-03],
       [ 0.00000000e+00, -5.54668245e-01,  7.32337039e-01, ...,
        -9.57909817e-01,  0.00000000e+00, -5.18148626e-03],
       [ 0.00000000e+00, -1.62290651e+00, -9.89543275e-01, ...,
        -9.44545360e-01,  0.00000000e+00, -5.18148626e-03],
       ...,
       [ 0.00000000e+00, -5.54668245e-01, -9.71122773e-01, ...,
        -9.44545360e-01,  0.00000000e+00, -5.18148626e-03],
       [ 0.00000000e+00, -5.54668245e-01, -9.71122773e-01, ...,
        -9.44545360e-01,  0.00000000e+00, -5.18148626e-03],
       [ 0.00000000e+00,             nan,             nan, ...,
                    nan,             nan,  1.92994819e+02]])

In [51]:
Xscaled.mean()

np.float64(nan)

In [52]:
Xscaled.std()

np.float64(nan)

In [53]:
np.isnan(Xscaled).sum()

np.int64(34)

In [54]:
d.tail()

,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,target
37243,2048,6.0,39190.0,443.0,8.443,1726.0,13.0,204.429705,1.539737,132.769231,...,0.0,1726.0,614435.0,13.0,3257.0,3168.0,1.0,210.0,0.0,0
37244,2048,6.0,443.0,44050.0,0.436,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,259156585.0,0.0,219780.0,0.0,0.0,183.0,1.0,0.0,0
37245,2048,6.0,443.0,49426.0,8.430,6205.0,8.0,736.061684,0.948992,775.625000,...,0.0,263216991.0,13841.0,223460.0,15.0,8.0,162.0,2.0,0.0,0
37246,2048,6.0,443.0,49536.0,8.427,5656.0,13.0,671.175982,1.542660,435.076923,...,0.0,263216991.0,14354.0,223460.0,30.0,13.0,162.0,2.0,0.0,0
37247,2048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [55]:
d.fillna(0)

,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,target
0,2048,6.0,22.0,41410.0,6.472,113472.0,628.0,17532.756490,97.033375,180.687898,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,0
1,2048,6.0,41410.0,22.0,6.465,24492.0,370.0,3788.399072,57.231245,66.194595,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,0
2,2048,1.0,0.0,0.0,4.798,2211.0,4.0,460.817007,0.833681,552.750000,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,0
3,2048,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,18189.757590,43.051052,422.515979,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,0
4,2048,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,259641.132900,192.698542,1347.395418,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37243,2048,6.0,39190.0,443.0,8.443,1726.0,13.0,204.429705,1.539737,132.769231,...,0.0,1726.0,614435.0,13.0,3257.0,3168.0,1.0,210.0,0.0,0
37244,2048,6.0,443.0,44050.0,0.436,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,259156585.0,0.0,219780.0,0.0,0.0,183.0,1.0,0.0,0
37245,2048,6.0,443.0,49426.0,8.430,6205.0,8.0,736.061684,0.948992,775.625000,...,0.0,263216991.0,13841.0,223460.0,15.0,8.0,162.0,2.0,0.0,0
37246,2048,6.0,443.0,49536.0,8.427,5656.0,13.0,671.175982,1.542660,435.076923,...,0.0,263216991.0,14354.0,223460.0,30.0,13.0,162.0,2.0,0.0,0
37247,2048,0.0,0.0,0.0,0.000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [56]:
X_train,X_test,Y_train,Y_test=train_test_split(Xscaled,labels,test_size=0.2,random_state=2)

In [57]:
X_train

array([[ 0.        , -0.55466825, -0.97112277, ..., -0.89108753,
         0.        , -0.00518149],
       [ 0.        ,  1.79545595, -0.98733947, ..., -0.583705  ,
         0.        , -0.00518149],
       [ 0.        ,  1.79545595,  1.25447302, ..., -0.583705  ,
         0.        , -0.00518149],
       ...,
       [ 0.        , -0.55466825,  1.24952485, ...,  1.52787935,
         0.        , -0.00518149],
       [ 0.        , -0.55466825,  1.37518344, ...,  0.77946971,
         0.        , -0.00518149],
       [ 0.        ,  1.79545595,  0.5126632 , ...,  1.04675887,
         0.        , -0.00518149]])

In [58]:
Y_train

array([0, 0, 0, ..., 0, 0, 0])

In [59]:
print(Y_train)

[0 0 0 ... 0 0 0]

In [60]:
scaler=StandardScaler()

In [61]:
X_train=scaler.fit_transform(X_train)

In [62]:
X_train

array([[ 0.00000000e+00, -5.55456482e-01, -9.71553007e-01, ...,
        -8.92323443e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00,  1.79239402e+00, -9.87776205e-01, ...,
        -5.84917314e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00,  1.79239402e+00,  1.25493528e+00, ...,
        -5.84917314e-01,  0.00000000e+00, -7.97972799e-17],
       ...,
       [ 0.00000000e+00, -5.55456482e-01,  1.24998512e+00, ...,
         1.52682913e+00,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00, -5.55456482e-01,  1.37569410e+00, ...,
         7.78362038e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00,  1.79239402e+00,  5.12827979e-01, ...,
         1.04567171e+00,  0.00000000e+00, -7.97972799e-17]])

In [63]:
X_test=scaler.transform(X_test)

In [64]:
X_test

array([[ 0.00000000e+00, -5.55456482e-01,  5.52387623e-01, ...,
        -1.70587315e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00, -5.55456482e-01,  6.05133814e-01, ...,
         1.55356010e+00,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00, -5.55456482e-01, -9.71553007e-01, ...,
        -9.59150862e-01,  0.00000000e+00, -7.97972799e-17],
       ...,
       [ 0.00000000e+00, -5.55456482e-01, -9.71553007e-01, ...,
        -9.59150862e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00,  1.79239402e+00, -9.87776205e-01, ...,
        -6.65110217e-01,  0.00000000e+00, -7.97972799e-17],
       [ 0.00000000e+00, -5.55456482e-01, -9.71553007e-01, ...,
        -9.59150862e-01,  0.00000000e+00, -7.97972799e-17]])

In [65]:
X_train.mean()

np.float64(-1.4966910211381846e-16)

In [66]:
X_train.std()

np.float64(0.957427107756309)

In [67]:
from sklearn.linear_model import LogisticRegression

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
model

LogisticRegression(max_iter=1000)