<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day2and3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
normal=pd.read_csv('/content/SDNFlow_Dataset_Normal.csv')

In [ ]:
attack=pd.read_csv('/content/SDNFlow_Dataset_attack.csv')

In [ ]:
d=pd.concat([normal,attack],axis=0)

In [ ]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6.0,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6.0,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1.0,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,STREAMING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43602,43603,2048,23.19.211.137,10.10.10.16,6.0,2935.0,135.0,0.810,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43603,43604,2048,34.186.92.15,10.10.10.16,6.0,2940.0,135.0,0.780,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43604,43605,2048,61.109.254.142,10.10.10.16,6.0,2948.0,135.0,0.750,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43605,43606,2048,15.92.67.78,10.10.10.16,6.0,2952.0,135.0,0.740,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43606,43607,2048,212.143.254.95,10.10.10.16,6.0,2956.0,135.0,0.720,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d['Attack'].value_counts()

Attack
1.0    43606
0.0    37247
Name: count, dtype: int64

In [ ]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6.0,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6.0,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1.0,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17.0,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17.0,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,STREAMING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43602,43603,2048,23.19.211.137,10.10.10.16,6.0,2935.0,135.0,0.810,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43603,43604,2048,34.186.92.15,10.10.10.16,6.0,2940.0,135.0,0.780,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43604,43605,2048,61.109.254.142,10.10.10.16,6.0,2948.0,135.0,0.750,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43605,43606,2048,15.92.67.78,10.10.10.16,6.0,2952.0,135.0,0.740,0.0,0.0,...,0.0,25752.0,0.0,148.0,0.0,148.0,282.0,1.0,1.0,ddos
43606,43607,2048,212.143.254.95,10.10.10.16,6.0,2956.0,135.0,0.720,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d = d.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,14188,2048,8.43.72.98,192.168.56.203,6.0,443.0,37004.0,0.385,0.0,0.0,...,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,0.0,HTTP
1,29086,2048,192.168.56.203,95.101.29.75,6.0,43496.0,80.0,6.747,547.0,2.0,...,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,0.0,HTTP
2,28055,2048,10.10.10.4,195.207.16.142,6.0,5432.0,1537.0,0.443,0.0,0.0,...,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,1.0,ddos
3,43515,2048,10.10.10.16,159.241.250.220,6.0,88.0,3030.0,0.183,0.0,0.0,...,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,1.0,ddos
4,8701,2048,192.168.56.203,52.95.126.138,6.0,38224.0,443.0,0.338,0.0,0.0,...,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,0.0,HTTP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80850,6266,2048,192.168.56.203,18.155.248.84,6.0,35006.0,443.0,0.238,288.0,3.0,...,0.0,288.0,288554.0,3.0,701.0,524.0,1.0,83.0,0.0,HTTP
80851,17639,2048,10.10.10.4,119.196.238.92,6.0,23.0,2897.0,0.587,0.0,0.0,...,0.0,0.0,8640.0,0.0,144.0,0.0,1.0,120.0,1.0,ddos
80852,39573,2048,10.10.10.12,88.252.254.23,6.0,464.0,1411.0,0.640,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,90.0,1.0,ddos
80853,861,2048,216.239.34.178,192.168.56.203,6.0,443.0,49102.0,0.969,0.0,0.0,...,0.0,42009310.0,0.0,34244.0,0.0,0.0,87.0,1.0,0.0,HTTP
80854,15796,2048,157.240.6.23,192.168.56.203,6.0,443.0,46498.0,0.790,66.0,1.0,...,0.0,141238955.0,132.0,119506.0,2.0,1.0,130.0,2.0,0.0,HTTP

In [ ]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ipv4_src                 1
ipv4_dst                 1
ip_proto                 1
src_port                 1
dst_port                 1
flow_duration            1
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     2
active_max               2
active_mean              2
active_min               2
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 2
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder=LabelEncoder()

In [ ]:
attacktypes=labelencoder.fit_transform(d.Category)

In [ ]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,14188,2048,8.43.72.98,192.168.56.203,6.0,443.0,37004.0,0.385,0.0,0.0,...,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,0.0,HTTP
1,29086,2048,192.168.56.203,95.101.29.75,6.0,43496.0,80.0,6.747,547.0,2.0,...,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,0.0,HTTP
2,28055,2048,10.10.10.4,195.207.16.142,6.0,5432.0,1537.0,0.443,0.0,0.0,...,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,1.0,ddos
3,43515,2048,10.10.10.16,159.241.250.220,6.0,88.0,3030.0,0.183,0.0,0.0,...,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,1.0,ddos
4,8701,2048,192.168.56.203,52.95.126.138,6.0,38224.0,443.0,0.338,0.0,0.0,...,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,0.0,HTTP

In [ ]:
d['Category']=labelencoder.fit_transform(d['Category'])

In [ ]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,14188,2048,8.43.72.98,192.168.56.203,6.0,443.0,37004.0,0.385,0.0,0.0,...,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,0.0,1
1,29086,2048,192.168.56.203,95.101.29.75,6.0,43496.0,80.0,6.747,547.0,2.0,...,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,0.0,1
2,28055,2048,10.10.10.4,195.207.16.142,6.0,5432.0,1537.0,0.443,0.0,0.0,...,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,1.0,5
3,43515,2048,10.10.10.16,159.241.250.220,6.0,88.0,3030.0,0.183,0.0,0.0,...,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,1.0,5
4,8701,2048,192.168.56.203,52.95.126.138,6.0,38224.0,443.0,0.338,0.0,0.0,...,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,0.0,1

In [ ]:
d.drop(columns=['ipv4_src','ipv4_dst'],inplace=True)

In [ ]:
d.head()

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,14188,2048,6.0,443.0,37004.0,0.385,0.0,0.0,0.00000,0.000000,...,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,0.0,1
1,29086,2048,6.0,43496.0,80.0,6.747,547.0,2.0,81.07307,0.296428,...,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,0.0,1
2,28055,2048,6.0,5432.0,1537.0,0.443,0.0,0.0,0.00000,0.000000,...,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,1.0,5
3,43515,2048,6.0,88.0,3030.0,0.183,0.0,0.0,0.00000,0.000000,...,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,1.0,5
4,8701,2048,6.0,38224.0,443.0,0.338,0.0,0.0,0.00000,0.000000,...,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,0.0,1

In [ ]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 1
src_port                 1
dst_port                 1
flow_duration            1
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     2
active_max               2
active_mean              2
active_min               2
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 0
dtype: int64

In [ ]:
d['src_port'].fillna(d['src_port'].median(),inplace=True)

/tmp/ipykernel_6356/293307303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['src_port'].fillna(d['src_port'].median(),inplace=True)

In [ ]:
d['src_port'].isnull().sum()

np.int64(0)

In [ ]:
d['dst_port'].fillna(d['dst_port'].median(),inplace=True)

/tmp/ipykernel_6356/178196058.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['dst_port'].fillna(d['dst_port'].median(),inplace=True)

In [ ]:
d['dst_port'].value_counts()

dst_port
443.0      12760
53.0        4830
80.0        1680
445.0       1345
139.0       1320
           ...
42626.0        1
34870.0        1
41781.0        1
45454.0        1
35710.0        1
Name: count, Length: 10385, dtype: int64

In [ ]:
d['dst_port'].isnull().sum()

np.int64(0)

In [ ]:
d['flow_duration'].fillna(d['flow_duration'].median(),inplace=True)

/tmp/ipykernel_6356/4117501463.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_duration'].fillna(d['flow_duration'].median(),inplace=True)

In [ ]:
d['flow_duration'].isnull().sum()

np.int64(0)

In [ ]:
d.head()

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,14188,2048,6.0,443.0,37004.0,0.385,0.0,0.0,0.00000,0.000000,...,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,0.0,1
1,29086,2048,6.0,43496.0,80.0,6.747,547.0,2.0,81.07307,0.296428,...,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,0.0,1
2,28055,2048,6.0,5432.0,1537.0,0.443,0.0,0.0,0.00000,0.000000,...,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,1.0,5
3,43515,2048,6.0,88.0,3030.0,0.183,0.0,0.0,0.00000,0.000000,...,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,1.0,5
4,8701,2048,6.0,38224.0,443.0,0.338,0.0,0.0,0.00000,0.000000,...,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,0.0,1

In [ ]:
d['flow_duration'].isnull().sum()

np.int64(0)

In [ ]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 1
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     2
active_max               2
active_mean              2
active_min               2
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 0
dtype: int64

In [ ]:
d['tot_pkts'].median()

1.0

In [ ]:
d['tot_len_pkts'].fillna(d['tot_len_pkts'].median(),inplace=True)

/tmp/ipykernel_6356/3595420504.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['tot_len_pkts'].fillna(d['tot_len_pkts'].median(),inplace=True)

In [ ]:
d['tot_len_pkts'].isnull().sum()

np.int64(0)

In [ ]:
d['tot_pkts'].fillna(d['tot_pkts'].median(),inplace=True)

/tmp/ipykernel_6356/666301824.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['tot_pkts'].fillna(d['tot_pkts'].median(),inplace=True)

In [ ]:
d['tot_pkts'].isnull().sum()

np.int64(0)

In [ ]:
d['flow_byts_s'].fillna(d['flow_byts_s'].median(),inplace=True)

/tmp/ipykernel_6356/2186293361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_byts_s'].fillna(d['flow_byts_s'].median(),inplace=True)

In [ ]:
d['flow_byts_s'].isnull().sum()

np.int64(0)

In [ ]:
d['flow_pkts_s'].fillna(d['flow_pkts_s'].median(),inplace=True)

/tmp/ipykernel_6356/3816719917.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_pkts_s'].fillna(d['flow_pkts_s'].median(),inplace=True)

In [ ]:
d['flow_pkts_s'].isnull().sum()

np.int64(0)

In [ ]:
d['Byts_max_interval_2s'].fillna(d['Byts_max_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/3006632629.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_max_interval_2s'].fillna(d['Byts_max_interval_2s'].median(),inplace=True)

In [ ]:
d['Byts_max_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Byts_min_interval_2s'].fillna(d['Byts_min_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/4286685733.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_min_interval_2s'].fillna(d['Byts_min_interval_2s'].median(),inplace=True)

In [ ]:
d['Byts_min_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Byts_mean_interval_2s'].fillna(d['Byts_mean_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/3633680940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_mean_interval_2s'].fillna(d['Byts_mean_interval_2s'].median(),inplace=True)

In [ ]:
d['Byts_mean_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Byts_std_interval_2s'].fillna(d['Byts_std_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/3877808458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_std_interval_2s'].fillna(d['Byts_std_interval_2s'].median(),inplace=True)

In [ ]:
d['Byts_std_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Pkts_max_interval_2s'].fillna(d['Pkts_max_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/264070740.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_max_interval_2s'].fillna(d['Pkts_max_interval_2s'].median(),inplace=True)

In [ ]:
d['Pkts_max_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Pkts_min_interval_2s'].fillna(d['Pkts_min_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/1286988706.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_min_interval_2s'].fillna(d['Pkts_min_interval_2s'].median(),inplace=True)

In [ ]:
d['Pkts_min_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Pkts_mean_interval_2s'].fillna(d['Pkts_mean_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/2727627611.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_mean_interval_2s'].fillna(d['Pkts_mean_interval_2s'].median(),inplace=True)

In [ ]:
d['Pkts_mean_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['Pkts_std_interval_2s'].fillna(d['Pkts_std_interval_2s'].median(),inplace=True)

/tmp/ipykernel_6356/3691687667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_std_interval_2s'].fillna(d['Pkts_std_interval_2s'].median(),inplace=True)

In [ ]:
d['Pkts_std_interval_2s'].isnull().sum()

np.int64(0)

In [ ]:
d['pkt_size_average'].fillna(d['pkt_size_average'].median(),inplace=True)

/tmp/ipykernel_6356/2293475368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['pkt_size_average'].fillna(d['pkt_size_average'].median(),inplace=True)

In [ ]:
d['pkt_size_average'].isnull().sum()

np.int64(0)

In [ ]:
d['fwd_header_len'].isnull().sum()

np.int64(1)

In [ ]:
d['fwd_header_len'].fillna(d['fwd_header_len'].median(),inplace=True)

/tmp/ipykernel_6356/1316340972.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['fwd_header_len'].fillna(d['fwd_header_len'].median(),inplace=True)

In [ ]:
d['fwd_header_len'].isnull().sum()

np.int64(0)

In [ ]:
d['active_max'].fillna(d['active_max'].median(),inplace=True)

/tmp/ipykernel_6356/476798417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_max'].fillna(d['active_max'].median(),inplace=True)

In [ ]:
d['active_max'].isnull().sum()

np.int64(0)

In [ ]:
d['active_mean'].fillna(d['active_mean'].median(),inplace=True)

/tmp/ipykernel_6356/1271949873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_mean'].fillna(d['active_mean'].median(),inplace=True)

In [ ]:
d['active_mean'].isnull().sum()

np.int64(0)

In [ ]:
d['active_min'].fillna(d['active_min'].median(),inplace=True)

/tmp/ipykernel_6356/1982822974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_min'].fillna(d['active_min'].median(),inplace=True)

In [ ]:
d['active_min'].isnull().sum()

np.int64(0)

In [ ]:
d['active_std'].fillna(d['active_std'].median(),inplace=True)

/tmp/ipykernel_6356/1219665179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_std'].fillna(d['active_std'].median(),inplace=True)

In [ ]:
d['active_std'].isnull().sum()

np.int64(0)

In [ ]:
d['idle_std'].fillna(d['idle_std'].median(),inplace=True)

/tmp/ipykernel_6356/1919844647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_std'].fillna(d['idle_std'].median(),inplace=True)

In [ ]:
d['idle_std'].isnull().sum()

np.int64(0)

In [ ]:
d['idle_min'].fillna(d['idle_min'].median(),inplace=True)

/tmp/ipykernel_6356/1407437676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_min'].fillna(d['idle_min'].median(),inplace=True)

In [ ]:
d['idle_mean'].fillna(d['idle_mean'].median(),inplace=True)

/tmp/ipykernel_6356/3194430402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_mean'].fillna(d['idle_mean'].median(),inplace=True)

In [ ]:
d['idle_max'].fillna(d['idle_max'].median(),inplace=True)

/tmp/ipykernel_6356/726970001.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_max'].fillna(d['idle_max'].median(),inplace=True)

In [ ]:
d['TnBPDstIP'].fillna(d['TnBPDstIP'].median(),inplace=True)

/tmp/ipykernel_6356/2836179091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnBPDstIP'].fillna(d['TnBPDstIP'].median(),inplace=True)

In [ ]:
d['TnBPSrcIP'].fillna(d['TnBPSrcIP'].median(),inplace=True)

/tmp/ipykernel_6356/2770195538.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnBPSrcIP'].fillna(d['TnBPSrcIP'].median(),inplace=True)

In [ ]:
d['TnPPDstIP'].fillna(d['TnPPDstIP'].median(),inplace=True)

/tmp/ipykernel_6356/3786267462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPDstIP'].fillna(d['TnPPDstIP'].median(),inplace=True)

In [ ]:
d['TnPPSrcIP'].fillna(d['TnPPSrcIP'].median(),inplace=True)

/tmp/ipykernel_6356/4003638087.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPSrcIP'].fillna(d['TnPPSrcIP'].median(),inplace=True)

In [ ]:
d['TnPPerDport'].fillna(d['TnPPerDport'].median(),inplace=True)

/tmp/ipykernel_6356/3856550780.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPerDport'].fillna(d['TnPPerDport'].median(),inplace=True)

In [ ]:
d['Tn_FlowsPDstIP'].fillna(d['Tn_FlowsPDstIP'].median(),inplace=True)

/tmp/ipykernel_6356/3052203981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Tn_FlowsPDstIP'].fillna(d['Tn_FlowsPDstIP'].median(),inplace=True)

In [ ]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 1
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           2
Attack                   2
Category                 0
dtype: int64

In [ ]:
d['Tn_FlowsPSrcIP'].fillna(d['Tn_FlowsPSrcIP'].median(),inplace=True)

/tmp/ipykernel_6356/3089895386.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Tn_FlowsPSrcIP'].fillna(d['Tn_FlowsPSrcIP'].median(),inplace=True)

In [ ]:
X=d.drop(columns='Attack',axis=1)
Y=d['Attack']

In [ ]:
X

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_min,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Category
0,14188,2048,6.0,443.0,37004.0,0.385,0.0,0.0,0.000000,0.000000,...,0.0,0.0,110354785.0,726.0,93144.0,11.0,0.0,179.0,4.0,1
1,29086,2048,6.0,43496.0,80.0,6.747,547.0,2.0,81.073070,0.296428,...,4.0,0.0,547.0,298467.0,2.0,2454.0,24.0,1.0,199.0,1
2,28055,2048,6.0,5432.0,1537.0,0.443,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,240.0,0.0,4.0,0.0,1.0,96.0,5
3,43515,2048,6.0,88.0,3030.0,0.183,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,3060.0,0.0,51.0,0.0,1.0,255.0,5
4,8701,2048,6.0,38224.0,443.0,0.338,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,305239.0,0.0,1353.0,1303.0,1.0,190.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80850,6266,2048,6.0,35006.0,443.0,0.238,288.0,3.0,1210.084034,12.605042,...,0.0,0.0,288.0,288554.0,3.0,701.0,524.0,1.0,83.0,1
80851,17639,2048,6.0,23.0,2897.0,0.587,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,8640.0,0.0,144.0,0.0,1.0,120.0,5
80852,39573,2048,6.0,464.0,1411.0,0.640,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,90.0,5
80853,861,2048,6.0,443.0,49102.0,0.969,0.0,0.0,0.000000,0.000000,...,0.0,0.0,42009310.0,0.0,34244.0,0.0,0.0,87.0,1.0,1
80854,15796,2048,6.0,443.0,46498.0,0.790,66.0,1.0,83.544304,1.265823,...,0.0,0.0,141238955.0,132.0,119506.0,2.0,1.0,130.0,2.0,1

In [ ]:
Y

0        0.0
1        0.0
2        1.0
3        1.0
4        0.0
        ...
80850    0.0
80851    1.0
80852    1.0
80853    0.0
80854    0.0
Name: Attack, Length: 80855, dtype: float64

In [ ]:
Y.isnull().sum()

np.int64(2)

In [ ]:
Y.isnull().sum()

np.int64(2)

In [ ]:
Y.median()

1.0

In [ ]:
Y.fillna(Y.median(),inplace=True)

In [ ]:
Y

0        0.0
1        0.0
2        1.0
3        1.0
4        0.0
        ...
80850    0.0
80851    1.0
80852    1.0
80853    0.0
80854    0.0
Name: Attack, Length: 80855, dtype: float64

In [124]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [125]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [126]:
X_train

array([[-0.33241006,  0.        , -0.33396086, ..., -0.71539762,
         0.13047407, -0.97371456],
       [-0.40340638,  0.        , -0.33396086, ..., -0.71539762,
         1.65302142,  0.91150443],
       [-1.32593737,  0.        , -0.33396086, ..., -0.71539762,
        -0.39290158, -0.97371456],
       ...,
       [ 1.54726579,  0.        , -0.33396086, ..., -0.71539762,
        -0.1740354 ,  0.91150443],
       [ 0.91722613,  0.        , -0.33396086, ..., -0.35405476,
        -0.88772947, -0.97371456],
       [-0.78314823,  0.        , -0.33396086, ..., -0.68760201,
         0.84416814, -0.97371456]])

In [127]:
X_test

array([[-0.61479517,  0.        , -0.33396086, ..., -0.71539762,
         2.33816773,  0.91150443],
       [ 0.32457956,  0.        , -0.33396086, ..., -0.71539762,
        -0.21209909,  0.91150443],
       [ 1.46296293,  0.        , -0.33396086, ...,  0.1184705 ,
        -0.88772947,  0.91150443],
       ...,
       [ 0.87056901,  0.        , -0.33396086, ..., -0.71539762,
        -0.74499066,  0.91150443],
       [-0.28373169,  0.        , -0.33396086, ..., -0.70613241,
         0.90126366, -0.97371456],
       [ 0.22806499,  0.        , -0.33396086, ...,  0.98939943,
        -0.88772947,  0.91150443]])

In [128]:
Y_train

29128    0.0
51585    1.0
9978     0.0
69288    1.0
30145    1.0
        ...
80232    0.0
33867    1.0
31019    1.0
44566    0.0
72173    0.0
Name: Attack, Length: 64684, dtype: float64

In [129]:
Y_test

34340    1.0
4740     1.0
10606    1.0
50096    0.0
68493    1.0
        ...
8148     0.0
574      1.0
36215    1.0
44965    0.0
26109    1.0
Name: Attack, Length: 16171, dtype: float64

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
model=LogisticRegression()

In [132]:
model.fit(X_train,Y_train)

LogisticRegression()

In [133]:
model

LogisticRegression()

In [134]:
xdf=pd.DataFrame(X_test)

In [135]:
xdf

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,-0.614795,0.0,-0.333961,-0.713016,-0.578362,0.415154,-0.015866,-0.018479,-0.052595,-0.121221,...,1.961345,-0.300853,-0.448023,-0.045483,-0.447615,-0.054909,-0.117008,-0.715398,2.338168,0.911504
1,0.324580,0.0,-0.333961,-0.363528,-0.590464,0.441440,-0.015866,-0.018479,-0.052605,-0.121422,...,0.979318,1.854567,-0.448023,-0.046741,-0.447615,-0.079473,-0.117008,-0.715398,-0.212099,0.911504
2,1.462963,0.0,-0.333961,-0.589622,-0.356009,-0.192398,-0.015935,-0.019967,-0.052857,-0.126429,...,-0.493724,-0.300853,-0.448024,-0.047660,-0.447648,-0.097428,-0.117751,0.118471,-0.887729,0.911504
3,1.268249,0.0,-0.333961,1.208832,-0.652543,0.169002,-0.014671,-0.009546,-0.045073,-0.068046,...,-0.493724,-0.300853,-0.447903,0.011247,-0.446914,0.250582,0.864766,-0.696867,0.301761,-0.973715
4,1.006751,0.0,-0.333961,-0.640543,-0.573836,0.451082,-0.015866,-0.018479,-0.052608,-0.121492,...,0.979318,2.932278,-0.448023,-0.046140,-0.447615,-0.067752,-0.117008,-0.715398,0.672882,0.911504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16166,-1.057280,0.0,-0.333961,1.055211,-0.652543,0.563492,-0.012148,0.041816,-0.040976,0.049819,...,2.943373,-0.300853,-0.447933,0.008602,-0.446295,0.317291,1.071827,-0.715398,0.977391,-0.973715
16167,-1.686309,0.0,-0.333961,-0.644384,1.668181,-0.223638,-0.015935,-0.019967,-0.052857,-0.126429,...,-0.493724,-0.300853,-0.447866,-0.047660,-0.446572,-0.097428,-0.093216,0.099940,-0.887729,0.911504
16168,0.870569,0.0,-0.333961,-0.728107,-0.583222,0.469575,-0.015866,-0.018479,-0.052615,-0.121620,...,0.979318,1.854567,-0.448023,-0.047456,-0.447615,-0.093438,-0.117008,-0.715398,-0.744991,0.911504
16169,-0.283732,0.0,-0.333961,1.738916,-0.669838,-0.226148,-0.015547,-0.016990,0.016301,0.356612,...,-0.493724,-0.300853,-0.447990,-0.015860,-0.447452,0.097338,-0.100651,-0.706132,0.901264,-0.973715
16170,0.228065,0.0,-0.333961,-0.677683,-0.516139,-0.193851,-0.015935,-0.019967,-0.052857,-0.126429,...,-0.493724,-0.300853,-0.447627,-0.047660,-0.444910,-0.097428,-0.056785,0.989399,-0.887729,0.911504

In [136]:
X.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 1
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Category                 0
dtype: int64

In [137]:
d['ip_proto'].fillna(d['ip_proto'].median(),inplace=True)

/tmp/ipykernel_6356/3840301701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['ip_proto'].fillna(d['ip_proto'].median(),inplace=True)

In [140]:
xdf.fillna(xdf.median(),inplace=True)

In [143]:
x=pd.DataFrame(xdf)
a=x.to_numpy()

In [146]:
Y_pred=model.predict(a)

In [147]:
from sklearn.metrics import accuracy_score

In [148]:
accuracy_score(Y_test,Y_pred)

0.9999381609053244

In [151]:
Y.value_counts()

Attack
1.0    43608
0.0    37247
Name: count, dtype: int64

In [149]:
from sklearn.ensemble import RandomForestClassifier

In [150]:
import xgboost as xgb

In [152]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[7487,    1],
       [   0, 8683]])

In [160]:
from sklearn.pipeline import Pipeline

from category_encoders import TargetEncoder

In [159]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 2.6 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [161]:
from xgboost import XGBClassifier

In [162]:
xgb=XGBClassifier()

In [163]:
estimators=[('encoder',TargetEncoder()),('clf',XGBClassifier())]

In [164]:
pipe=Pipeline(steps=estimators)

In [165]:
pipe

Pipeline(steps=[('encoder', TargetEncoder()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [166]:
!pip install scikit_optimize

Collecting scikit_optimize
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.5.3)
Collecting pyaml>=16.9 (from scikit_optimize)
  Downloading pyaml-26.2.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (26.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit_optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit_optimize) (3.6.0)
Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 3.9 MB/s eta 0:00:00
Downloading pyaml-26.2.1-py3-none-any.whl (27 kB)
Installing collected packages: pyaml, scikit_optimize
Successfully installed pyaml-26.2.1 scikit_optimize-0.10.2

In [167]:
from skopt import BayesSearchCV

In [168]:
from skopt.space import Real,Categorical,Integer

In [169]:
search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [170]:
opt=BayesSearchCV(pipe,search_space,n_iter=100,cv=5,scoring='roc_auc',random_state=8)

In [172]:
from skopt import BayesSearchCV

In [173]:
opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=5
)

In [174]:
opt.fit(X_train,Y_train)

BayesSearchCV(cv=5,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [175]:
opt.best_params_

OrderedDict([('colsample_bytree', 0.883363879917018),
             ('gamma', 1.948034806965215),
             ('learning_rate', 0.013363792891261014),
             ('max_depth', 3),
             ('n_estimators', 181),
             ('reg_alpha', 0.15027680856619877),
             ('reg_lambda', 3.6162175542925397),
             ('subsample', 0.7515441455841694)])

In [176]:
opt.best_score_

np.float64(1.0)

In [177]:
opt.predict(X_test)

array([1, 1, 1, ..., 1, 0, 1])

In [178]:
opt.predict_proba(X_test)

array([[0.04169798, 0.958302  ],
       [0.04169798, 0.958302  ],
       [0.04169798, 0.958302  ],
       ...,
       [0.04169798, 0.958302  ],
       [0.9517845 , 0.04821549],
       [0.04169798, 0.958302  ]], dtype=float32)