In [1]:
import pandas as pd;
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
scaler=StandardScaler()
labelencoder=LabelEncoder()

In [5]:
d=pd.read_csv("C:/Internship_NITP/Train_ULAK.csv")

In [6]:
d.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,68855579,10,6,1038,11595,346,0,103.800000,167.133879,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,53,196,2,2,70,174,35,35,35.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,123,118,2,2,96,96,48,48,48.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,295657,7,10,1114,15841,1084,0,159.142857,407.829796,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,80,15705351,7,5,407,452,377,0,58.142857,140.620563,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [7]:
target = d[' Label']

In [8]:
Y=target

In [9]:
Y=labelencoder.fit_transform(target)

In [10]:
Y

array([4, 0, 0, ..., 3, 0, 0], shape=(724031,))

In [11]:
X=d

In [12]:
X.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,68855579,10,6,1038,11595,346,0,103.800000,167.133879,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,53,196,2,2,70,174,35,35,35.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,123,118,2,2,96,96,48,48,48.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,295657,7,10,1114,15841,1084,0,159.142857,407.829796,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,80,15705351,7,5,407,452,377,0,58.142857,140.620563,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [13]:
X.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [14]:
X=X.replace(np.nan,0,inplace=True)

In [15]:
X.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [124]:
np.isinf(X).sum()

 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    385
 Flow Packets/s                 725
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
dtype: int64

In [16]:
X=X.replace([np.inf, -np.inf], np.nan, inplace=True)

In [17]:
X.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,68855579,10,6,1038,11595,346,0,103.800000,167.133879,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,53,196,2,2,70,174,35,35,35.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,123,118,2,2,96,96,48,48,48.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,295657,7,10,1114,15841,1084,0,159.142857,407.829796,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,80,15705351,7,5,407,452,377,0,58.142857,140.620563,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [18]:
X.shape

(724031, 79)

In [19]:
Y.shape

(724031,)

In [20]:
Y

array([4, 0, 0, ..., 3, 0, 0], shape=(724031,))

In [21]:
X=X.drop(columns=' Destination Port')

In [22]:
X.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,196,2,2,70,174,35,35,35.000000,0.000000,87,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,118,2,2,96,96,48,48,48.000000,0.000000,48,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [23]:
X=X.drop(columns=[' Label'])

In [24]:
X.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,...,3,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000
1,196,2,2,70,174,35,35,35.000000,0.000000,87,...,1,32,0.0,0.0,0,0,0.0,0.0,0,0
2,118,2,2,96,96,48,48,48.000000,0.000000,48,...,1,20,0.0,0.0,0,0,0.0,0.0,0,0
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,...,6,20,0.0,0.0,0,0,0.0,0.0,0,0
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,...,6,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208

In [25]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [26]:
X_train.shape

(579224, 77)

In [27]:
Y_train

array([ 0, 10,  0, ..., 10,  0,  0], shape=(579224,))

In [28]:
e=pd.DataFrame(Y_train)

In [29]:
e.value_counts()

0
0     465262
4      47065
10     32607
2      26196
3       2118
7       1575
11      1247
6       1193
5       1116
1        380
12       307
14       149
9          6
13         2
8          1
Name: count, dtype: int64

In [30]:
e=e.replace([8,9,13],0)

In [31]:
e

         0
0        0
1       10
2        0
3       10
4        0
...     ..
579219   0
579220   4
579221  10
579222   0
579223   0

[579224 rows x 1 columns]

In [32]:
e.value_counts()

0
0     465271
4      47065
10     32607
2      26196
3       2118
7       1575
11      1247
6       1193
5       1116
1        380
12       307
14       149
Name: count, dtype: int64

In [33]:
e.shape

(579224, 1)

In [34]:
Y_train=e

In [35]:
Y_train.shape

(579224, 1)

In [36]:
X_train.shape

(579224, 77)

In [37]:
X_train=scaler.fit_transform(X_train)

In [38]:
X_test=scaler.transform(X_test)

In [1]:
from xgboost import XGBClassifier

In [2]:
xgb=XGBClassifier()

In [41]:
estimators=[('xgb',xgb)]

In [42]:
from sklearn.pipeline import Pipeline

In [43]:
pipe=Pipeline(estimators)

In [44]:
pip install scikit_optimize

Requirement already satisfied: scikit_optimize in c:\users\quant\miniconda3\lib\site-packages (0.10.2)
Requirement already satisfied: joblib>=0.11 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (1.5.3)
Requirement already satisfied: pyaml>=16.9 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (26.2.1)
Requirement already satisfied: numpy>=1.20.3 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (2.4.3)
Requirement already satisfied: scipy>=1.1.0 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (1.17.1)
Requirement already satisfied: scikit-learn>=1.0.0 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (1.8.0)
Requirement already satisfied: packaging>=21.3 in c:\users\quant\miniconda3\lib\site-packages (from scikit_optimize) (25.0)
Requirement already satisfied: PyYAML in c:\users\quant\miniconda3\lib\site-packages (from pyaml>=16.9->scikit_optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\quant\miniconda3\lib\site-packages (from scikit-learn>=1.0.0->scikit_optimize) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [45]:
from skopt import BayesSearchCV

In [46]:
from skopt.space import Real,Categorical,Integer

In [47]:
search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [48]:
opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=2,scoring='roc_auc',random_state=8)

In [49]:
opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=2)

In [50]:
Y_train=labelencoder.fit_transform(Y_train)

c:\Users\quant\miniconda3\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [51]:
Y_train.shape

(579224,)

In [52]:
opt.fit(X_train,Y_train)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [53]:
from sklearn.metrics import classification_report

# Predictions
Y_pred = opt.predict(X_test)

# Classification report
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    116377
           1       0.93      0.72      0.81       107
           2       1.00      1.00      1.00      6483
           3       0.99      0.99      0.99       517
           4       1.00      1.00      1.00     11725
           5       0.95      0.99      0.97       282
           6       1.00      0.99      1.00       288
           7       1.00      1.00      1.00       413
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         3
          10       0.00      0.00      0.00      8193
          11       0.00      0.00      0.00       311
          12       0.00      0.00      0.00        75
          13       0.00      0.00      0.00         4
          14       0.00      0.00      0.00        29

    accuracy                           0.94    144807
   macro avg       0.52      0.51      0.52    144807
weighted avg       0.94      0.94      0.94    144807

c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\quant\miniconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
accuracy_score(Y_test, Y_pred)

0.9393261375485992

In [56]:
test=pd.read_csv("C:/Internship_NITP/Test_ULAK.csv")

In [57]:
test.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,998,2,0,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
1,80,63111103,7,0,0,0,0,0,0.0,0.0,...,40,7015565.0,0.0,7015565,7015565,18700000.0,12200000.0,32100000,8015910,DoS Slowhttptest
2,53,202,2,2,98,130,49,49,49.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,3,2,0,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
4,7200,37,1,1,0,6,0,0,0.0,0.0,...,40,0.0,0.0,0,0,0.0,0.0,0,0,PortScan

In [58]:
t1=test.drop(columns=[' Destination Port'])

In [59]:
t1.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,998,2,0,0,0,0,0,0.0,0.0,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
1,63111103,7,0,0,0,0,0,0.0,0.0,0,...,40,7015565.0,0.0,7015565,7015565,18700000.0,12200000.0,32100000,8015910,DoS Slowhttptest
2,202,2,2,98,130,49,49,49.0,0.0,65,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,3,2,0,0,0,0,0,0.0,0.0,0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,DoS Hulk
4,37,1,1,0,6,0,0,0.0,0.0,6,...,40,0.0,0.0,0,0,0.0,0.0,0,0,PortScan

In [60]:
Yt=test[' Label']

In [61]:
t1=test.drop(columns=[' Label',' Destination Port'])

In [76]:
t1.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,998,2,0,0,0,0,0,0.0,0.0,0,...,0,32,0.0,0.0,0,0,0.0,0.0,0,0
1,63111103,7,0,0,0,0,0,0.0,0.0,0,...,0,40,7015565.0,0.0,7015565,7015565,18700000.0,12200000.0,32100000,8015910
2,202,2,2,98,130,49,49,49.0,0.0,65,...,1,20,0.0,0.0,0,0,0.0,0.0,0,0
3,3,2,0,0,0,0,0,0.0,0.0,0,...,0,32,0.0,0.0,0,0,0.0,0.0,0,0
4,37,1,1,0,6,0,0,0.0,0.0,6,...,0,40,0.0,0.0,0,0,0.0,0.0,0,0

In [62]:
Yt

0                 DoS Hulk
1         DoS Slowhttptest
2                   BENIGN
3                 DoS Hulk
4                 PortScan
                ...
512072            DoS Hulk
512073              BENIGN
512074            DoS Hulk
512075            DoS Hulk
512076              BENIGN
Name:  Label, Length: 512077, dtype: str

In [63]:
Yt=labelencoder.fit_transform(Yt)

In [64]:
Yt

array([4, 5, 0, ..., 4, 4, 0], shape=(512077,))

In [65]:
t1.shape

(512077, 77)

In [66]:
t1.isnull().sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
                               ..
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
Length: 77, dtype: int64

In [68]:
pd.set_option('display.max_columns', None)

In [69]:
pd.set_option('display.max_rows', None)

In [70]:
t1.isnull().sum()

 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    249
 Flow Packets/s                   0
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
dtype: int64

In [71]:
t1['Flow Bytes/s']=t1['Flow Bytes/s'].replace([np.inf, -np.inf], t1['Flow Bytes/s'].median())

In [72]:
t1.shape

(512077, 77)

In [73]:
np.isinf(t1).sum()

 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                      0
 Flow Packets/s                 537
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
dtype: int64

In [74]:
t1=t1.replace([np.inf, -np.inf],0)

In [75]:
np.isinf(t1).sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
 Fwd Packet Length Max          0
 Fwd Packet Length Min          0
 Fwd Packet Length Mean         0
 Fwd Packet Length Std          0
Bwd Packet Length Max           0
 Bwd Packet Length Min          0
 Bwd Packet Length Mean         0
 Bwd Packet Length Std          0
Flow Bytes/s                    0
 Flow Packets/s                 0
 Flow IAT Mean                  0
 Flow IAT Std                   0
 Flow IAT Max                   0
 Flow IAT Min                   0
Fwd IAT Total                   0
 Fwd IAT Mean                   0
 Fwd IAT Std                    0
 Fwd IAT Max                    0
 Fwd IAT Min                    0
Bwd IAT Total                   0
 Bwd IAT Mean                   0
 Bwd IAT Std                    0
 Bwd IAT Max                    0
 Bwd IAT Min                    0
Fwd PSH Flags                   0
 Bwd PSH Flags                  0
 Fwd URG Flags                  0
 Bwd URG Flags                  0
 Fwd Header Length              0
 Bwd Header Length              0
Fwd Packets/s                   0
 Bwd Packets/s                  0
 Min Packet Length              0
 Max Packet Length              0
 Packet Length Mean             0
 Packet Length Std              0
 Packet Length Variance         0
FIN Flag Count                  0
 SYN Flag Count                 0
 RST Flag Count                 0
 PSH Flag Count                 0
 ACK Flag Count                 0
 URG Flag Count                 0
 CWE Flag Count                 0
 ECE Flag Count                 0
 Down/Up Ratio                  0
 Average Packet Size            0
 Avg Fwd Segment Size           0
 Avg Bwd Segment Size           0
 Fwd Header Length.1            0
Fwd Avg Bytes/Bulk              0
 Fwd Avg Packets/Bulk           0
 Fwd Avg Bulk Rate              0
 Bwd Avg Bytes/Bulk             0
 Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
 Subflow Fwd Bytes              0
 Subflow Bwd Packets            0
 Subflow Bwd Bytes              0
Init_Win_bytes_forward          0
 Init_Win_bytes_backward        0
 act_data_pkt_fwd               0
 min_seg_size_forward           0
Active Mean                     0
 Active Std                     0
 Active Max                     0
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
dtype: int64

In [76]:
e=pd.DataFrame(Yt)

In [77]:
e.isnull().sum()

0    0
dtype: int64

In [78]:
np.isinf(e).sum()

0    0
dtype: int64

In [79]:
t1_scaler=scaler.transform(t1)

In [80]:
t1.isnull().sum()

 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    249
 Flow Packets/s                   0
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
dtype: int64

In [81]:
t1=t1.fillna(0)

In [82]:
t1.isnull().sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
 Fwd Packet Length Max          0
 Fwd Packet Length Min          0
 Fwd Packet Length Mean         0
 Fwd Packet Length Std          0
Bwd Packet Length Max           0
 Bwd Packet Length Min          0
 Bwd Packet Length Mean         0
 Bwd Packet Length Std          0
Flow Bytes/s                    0
 Flow Packets/s                 0
 Flow IAT Mean                  0
 Flow IAT Std                   0
 Flow IAT Max                   0
 Flow IAT Min                   0
Fwd IAT Total                   0
 Fwd IAT Mean                   0
 Fwd IAT Std                    0
 Fwd IAT Max                    0
 Fwd IAT Min                    0
Bwd IAT Total                   0
 Bwd IAT Mean                   0
 Bwd IAT Std                    0
 Bwd IAT Max                    0
 Bwd IAT Min                    0
Fwd PSH Flags                   0
 Bwd PSH Flags                  0
 Fwd URG Flags                  0
 Bwd URG Flags                  0
 Fwd Header Length              0
 Bwd Header Length              0
Fwd Packets/s                   0
 Bwd Packets/s                  0
 Min Packet Length              0
 Max Packet Length              0
 Packet Length Mean             0
 Packet Length Std              0
 Packet Length Variance         0
FIN Flag Count                  0
 SYN Flag Count                 0
 RST Flag Count                 0
 PSH Flag Count                 0
 ACK Flag Count                 0
 URG Flag Count                 0
 CWE Flag Count                 0
 ECE Flag Count                 0
 Down/Up Ratio                  0
 Average Packet Size            0
 Avg Fwd Segment Size           0
 Avg Bwd Segment Size           0
 Fwd Header Length.1            0
Fwd Avg Bytes/Bulk              0
 Fwd Avg Packets/Bulk           0
 Fwd Avg Bulk Rate              0
 Bwd Avg Bytes/Bulk             0
 Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
 Subflow Fwd Bytes              0
 Subflow Bwd Packets            0
 Subflow Bwd Bytes              0
Init_Win_bytes_forward          0
 Init_Win_bytes_backward        0
 act_data_pkt_fwd               0
 min_seg_size_forward           0
Active Mean                     0
 Active Std                     0
 Active Max                     0
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
dtype: int64

In [83]:
t1_scale=scaler.transform(t1)

In [85]:
t1.shape

(512077, 77)

In [86]:
Yt.shape

(512077,)

In [87]:
opt.fit(t1,Yt)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [93]:
yp=opt.predict(t1)

In [99]:
accuracy_score(Yt,yp)

0.9985724803105783