<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import seaborn as sns

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
normal=pd.read_csv('/content/SDNFlow_Dataset_Normal.csv')

In [8]:
attack=pd.read_csv('/content/SDNFlow_Dataset_attack.csv')

In [9]:
d=pd.concat([normal,attack],axis=0)

In [10]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,STREAMING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176730,176731,2048,172.20.0.100,10.10.10.80,6,57274.0,80.0,17.544,1320.0,16.0,...,0.0,308941.0,308941.0,3912.0,3912.0,3912.0,188.0,188.0,1.0,dos
176731,176732,2048,10.10.10.80,172.20.0.100,6,80.0,57128.0,14.713,1294.0,13.0,...,0.0,257278.0,257278.0,2831.0,2831.0,13.0,180.0,180.0,1.0,dos
176732,176733,2048,172.20.0.100,10.10.10.80,6,57276.0,80.0,12.933,1183.0,14.0,...,0.0,237345.0,237345.0,2847.0,2847.0,2847.0,189.0,189.0,1.0,dos
176733,176734,2048,10.10.10.80,172.20.0.100,6,80.0,57144.0,13.933,1096.0,10.0,...,0.0,234010.0,234010.0,2551.0,2551.0,10.0,183.0,183.0,1.0,dos
176734,176735,2048,172.20.0.100,10.10.10.80,6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
d['Attack'].value_counts()

Attack
1.0    176734
0.0    175690
Name: count, dtype: int64

In [12]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22.0,41410.0,6.472,113472.0,628.0,...,0.0,113472.0,7295988.0,628.0,6659.0,628.0,1.0,10.0,0.0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410.0,22.0,6.465,24492.0,370.0,...,0.0,26080.0,24492.0,381.0,370.0,370.0,2.0,1.0,0.0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0.0,0.0,4.798,2211.0,4.0,...,0.0,28291.0,3799.0,385.0,15.0,0.0,3.0,2.0,0.0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426.0,1236.0,595.270,10827817.0,25627.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,30743.0,60.0,19.0,0.0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549.0,1234.0,595.251,154551644.0,114704.0,...,0.0,188960322.0,180776253.0,157117.0,153898.0,122654.0,60.0,19.0,0.0,STREAMING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176730,176731,2048,172.20.0.100,10.10.10.80,6,57274.0,80.0,17.544,1320.0,16.0,...,0.0,308941.0,308941.0,3912.0,3912.0,3912.0,188.0,188.0,1.0,dos
176731,176732,2048,10.10.10.80,172.20.0.100,6,80.0,57128.0,14.713,1294.0,13.0,...,0.0,257278.0,257278.0,2831.0,2831.0,13.0,180.0,180.0,1.0,dos
176732,176733,2048,172.20.0.100,10.10.10.80,6,57276.0,80.0,12.933,1183.0,14.0,...,0.0,237345.0,237345.0,2847.0,2847.0,2847.0,189.0,189.0,1.0,dos
176733,176734,2048,10.10.10.80,172.20.0.100,6,80.0,57144.0,13.933,1096.0,10.0,...,0.0,234010.0,234010.0,2551.0,2551.0,10.0,183.0,183.0,1.0,dos
176734,176735,2048,172.20.0.100,10.10.10.80,6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
d = d.sample(frac=1, random_state=42).reset_index(drop=True)

In [14]:
d

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,126363,2048,172.20.0.100,10.10.10.80,6,53068.0,3000.0,1.151,684.0,4.0,...,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,1.0,dos
1,37855,2048,10.10.10.4,135.226.138.227,6,8180.0,3300.0,7.353,120.0,2.0,...,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,1.0,ddos
2,40477,2048,173.194.217.154,192.168.56.203,6,443.0,41444.0,0.210,78.0,1.0,...,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,0.0,HTTP
3,125944,2048,172.20.0.100,10.10.10.80,6,50282.0,3000.0,6.695,544.0,4.0,...,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,1.0,dos
4,122609,2048,172.20.0.100,10.10.10.80,6,54504.0,80.0,1.456,601.0,4.0,...,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,1.0,dos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352421,119880,2048,3.213.224.199,192.168.56.203,6,443.0,35420.0,5.175,148.0,2.0,...,0.0,65276113.0,7517.0,55428.0,15.0,2.0,72.0,2.0,0.0,HTTP
352422,83488,2048,10.10.10.80,172.20.0.100,6,80.0,58154.0,3.980,743.0,4.0,...,0.0,138399.0,138399.0,752.0,752.0,4.0,185.0,185.0,1.0,dos
352423,131933,2048,192.168.56.203,200.24.19.252,17,60673.0,53.0,0.339,0.0,0.0,...,0.0,24168.0,55764.0,121.0,299.0,2.0,8.0,42.0,0.0,DNS
352424,146868,2048,142.250.78.35,192.168.56.203,6,80.0,37238.0,0.360,0.0,0.0,...,0.0,64637855.0,5396.0,54547.0,18.0,0.0,24.0,4.0,0.0,HTTP
352425,121959,2048,200.24.19.252,192.168.56.203,17,53.0,43210.0,2.304,0.0,0.0,...,0.0,109393585.0,269.0,92415.0,2.0,0.0,43.0,18.0,0.0,DNS

In [15]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ipv4_src                 0
ipv4_dst                 0
ip_proto                 0
src_port                 1
dst_port                 1
flow_duration            1
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     1
active_max               1
active_mean              1
active_min               1
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 2
dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
labelencoder=LabelEncoder()

In [25]:
attacktypes=labelencoder.fit_transform(d.Category)

In [31]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,126363,2048,172.20.0.100,10.10.10.80,6,53068.0,3000.0,1.151,684.0,4.0,...,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,1.0,dos
1,37855,2048,10.10.10.4,135.226.138.227,6,8180.0,3300.0,7.353,120.0,2.0,...,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,1.0,ddos
2,40477,2048,173.194.217.154,192.168.56.203,6,443.0,41444.0,0.210,78.0,1.0,...,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,0.0,HTTP
3,125944,2048,172.20.0.100,10.10.10.80,6,50282.0,3000.0,6.695,544.0,4.0,...,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,1.0,dos
4,122609,2048,172.20.0.100,10.10.10.80,6,54504.0,80.0,1.456,601.0,4.0,...,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,1.0,dos

In [32]:
d['Category']=labelencoder.fit_transform(d['Category'])

In [33]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,126363,2048,172.20.0.100,10.10.10.80,6,53068.0,3000.0,1.151,684.0,4.0,...,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,1.0,7
1,37855,2048,10.10.10.4,135.226.138.227,6,8180.0,3300.0,7.353,120.0,2.0,...,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,1.0,6
2,40477,2048,173.194.217.154,192.168.56.203,6,443.0,41444.0,0.210,78.0,1.0,...,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,0.0,2
3,125944,2048,172.20.0.100,10.10.10.80,6,50282.0,3000.0,6.695,544.0,4.0,...,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,1.0,7
4,122609,2048,172.20.0.100,10.10.10.80,6,54504.0,80.0,1.456,601.0,4.0,...,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,1.0,7

In [44]:
d.drop(columns=['ipv4_src','ipv4_dst'],inplace=True)

KeyError: "['ipv4_src', 'ipv4_dst'] not found in axis"

In [45]:
d.head()

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,126363,2048,6,53068.0,3000.0,1.151,684.0,4.0,594.265856,3.475239,...,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,1.0,7
1,37855,2048,6,8180.0,3300.0,7.353,120.0,2.0,16.319869,0.271998,...,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,1.0,6
2,40477,2048,6,443.0,41444.0,0.210,78.0,1.0,371.428571,4.761905,...,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,0.0,2
3,125944,2048,6,50282.0,3000.0,6.695,544.0,4.0,81.254668,0.597461,...,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,1.0,7
4,122609,2048,6,54504.0,80.0,1.456,601.0,4.0,412.774725,2.747253,...,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,1.0,7

In [38]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 0
src_port                 1
dst_port                 1
flow_duration            1
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     1
active_max               1
active_mean              1
active_min               1
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 0
dtype: int64

In [41]:
d['src_port'].fillna(d['src_port'].median(),inplace=True)

/tmp/ipykernel_3799/293307303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['src_port'].fillna(d['src_port'].median(),inplace=True)

In [43]:
d['src_port'].isnull().sum()

np.int64(0)

In [50]:
d['dst_port'].fillna(d['dst_port'].median(),inplace=True)

/tmp/ipykernel_3799/178196058.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['dst_port'].fillna(d['dst_port'].median(),inplace=True)

In [51]:
d['dst_port'].value_counts()

dst_port
443.0      56566
80.0       51808
53.0       21339
3000.0     19594
0.0        15499
           ...
42824.0        1
57083.0        1
40747.0        1
51283.0        1
35463.0        1
Name: count, Length: 23612, dtype: int64

In [52]:
d['dst_port'].isnull().sum()

np.int64(0)

In [53]:
d['flow_duration'].fillna(d['flow_duration'].median(),inplace=True)

/tmp/ipykernel_3799/4117501463.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_duration'].fillna(d['flow_duration'].median(),inplace=True)

In [55]:
d['flow_duration'].isnull().sum()

np.int64(0)

In [57]:
d.head()

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,126363,2048,6,53068.0,3000.0,1.151,684.0,4.0,594.265856,3.475239,...,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,1.0,7
1,37855,2048,6,8180.0,3300.0,7.353,120.0,2.0,16.319869,0.271998,...,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,1.0,6
2,40477,2048,6,443.0,41444.0,0.210,78.0,1.0,371.428571,4.761905,...,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,0.0,2
3,125944,2048,6,50282.0,3000.0,6.695,544.0,4.0,81.254668,0.597461,...,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,1.0,7
4,122609,2048,6,54504.0,80.0,1.456,601.0,4.0,412.774725,2.747253,...,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,1.0,7

In [58]:
d['flow_duration'].isnull().sum()

np.int64(0)

In [60]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 0
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             1
tot_pkts                 1
flow_byts_s              1
flow_pkts_s              1
pkt_size_average         1
fwd_header_len           1
Byts_max_interval_2s     1
Byts_min_interval_2s     1
Byts_mean_interval_2s    1
Byts_std_interval_2s     1
Pkts_max_interval_2s     1
Pkts_mean_interval_2s    1
Pkts_min_interval_2s     1
Pkts_std_interval_2s     1
active_max               1
active_mean              1
active_min               1
active_std               2
idle_max                 2
idle_mean                2
idle_min                 2
idle_std                 2
TnBPDstIP                2
TnBPSrcIP                2
TnPPDstIP                2
TnPPSrcIP                2
TnPPerDport              2
Tn_FlowsPDstIP           2
Tn_FlowsPSrcIP           2
Attack                   2
Category                 0
dtype: int64

In [63]:
d['tot_pkts'].median()

2.0

In [64]:
d['tot_len_pkts'].fillna(d['tot_len_pkts'].median(),inplace=True)

/tmp/ipykernel_3799/3595420504.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['tot_len_pkts'].fillna(d['tot_len_pkts'].median(),inplace=True)

In [65]:
d['tot_len_pkts'].isnull().sum()

np.int64(0)

In [66]:
d['tot_pkts'].fillna(d['tot_pkts'].median(),inplace=True)

/tmp/ipykernel_3799/666301824.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['tot_pkts'].fillna(d['tot_pkts'].median(),inplace=True)

In [67]:
d['tot_pkts'].isnull().sum()

np.int64(0)

In [68]:
d['flow_byts_s'].fillna(d['flow_byts_s'].median(),inplace=True)

/tmp/ipykernel_3799/2186293361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_byts_s'].fillna(d['flow_byts_s'].median(),inplace=True)

In [69]:
d['flow_byts_s'].isnull().sum()

np.int64(0)

In [70]:
d['flow_pkts_s'].fillna(d['flow_pkts_s'].median(),inplace=True)

/tmp/ipykernel_3799/3816719917.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['flow_pkts_s'].fillna(d['flow_pkts_s'].median(),inplace=True)

In [71]:
d['flow_pkts_s'].isnull().sum()

np.int64(0)

In [72]:
d['Byts_max_interval_2s'].fillna(d['Byts_max_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/3006632629.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_max_interval_2s'].fillna(d['Byts_max_interval_2s'].median(),inplace=True)

In [73]:
d['Byts_max_interval_2s'].isnull().sum()

np.int64(0)

In [74]:
d['Byts_min_interval_2s'].fillna(d['Byts_min_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/4286685733.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_min_interval_2s'].fillna(d['Byts_min_interval_2s'].median(),inplace=True)

In [75]:
d['Byts_min_interval_2s'].isnull().sum()

np.int64(0)

In [76]:
d['Byts_mean_interval_2s'].fillna(d['Byts_mean_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/3633680940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_mean_interval_2s'].fillna(d['Byts_mean_interval_2s'].median(),inplace=True)

In [77]:
d['Byts_mean_interval_2s'].isnull().sum()

np.int64(0)

In [78]:
d['Byts_std_interval_2s'].fillna(d['Byts_std_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/3877808458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Byts_std_interval_2s'].fillna(d['Byts_std_interval_2s'].median(),inplace=True)

In [79]:
d['Byts_std_interval_2s'].isnull().sum()

np.int64(0)

In [80]:
d['Pkts_max_interval_2s'].fillna(d['Pkts_max_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/264070740.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_max_interval_2s'].fillna(d['Pkts_max_interval_2s'].median(),inplace=True)

In [81]:
d['Pkts_max_interval_2s'].isnull().sum()

np.int64(0)

In [82]:
d['Pkts_min_interval_2s'].fillna(d['Pkts_min_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/1286988706.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_min_interval_2s'].fillna(d['Pkts_min_interval_2s'].median(),inplace=True)

In [83]:
d['Pkts_min_interval_2s'].isnull().sum()

np.int64(0)

In [84]:
d['Pkts_mean_interval_2s'].fillna(d['Pkts_mean_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/2727627611.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_mean_interval_2s'].fillna(d['Pkts_mean_interval_2s'].median(),inplace=True)

In [85]:
d['Pkts_mean_interval_2s'].isnull().sum()

np.int64(0)

In [87]:
d['Pkts_std_interval_2s'].fillna(d['Pkts_std_interval_2s'].median(),inplace=True)

/tmp/ipykernel_3799/3691687667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Pkts_std_interval_2s'].fillna(d['Pkts_std_interval_2s'].median(),inplace=True)

In [88]:
d['Pkts_std_interval_2s'].isnull().sum()

np.int64(0)

In [89]:
d['pkt_size_average'].fillna(d['pkt_size_average'].median(),inplace=True)

/tmp/ipykernel_3799/2293475368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['pkt_size_average'].fillna(d['pkt_size_average'].median(),inplace=True)

In [90]:
d['pkt_size_average'].isnull().sum()

np.int64(0)

In [91]:
d['fwd_header_len'].isnull().sum()

np.int64(1)

In [92]:
d['fwd_header_len'].fillna(d['fwd_header_len'].median(),inplace=True)

/tmp/ipykernel_3799/1316340972.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['fwd_header_len'].fillna(d['fwd_header_len'].median(),inplace=True)

In [93]:
d['fwd_header_len'].isnull().sum()

np.int64(0)

In [94]:
d['active_max'].fillna(d['active_max'].median(),inplace=True)

/tmp/ipykernel_3799/476798417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_max'].fillna(d['active_max'].median(),inplace=True)

In [95]:
d['active_max'].isnull().sum()

np.int64(0)

In [96]:
d['active_mean'].fillna(d['active_mean'].median(),inplace=True)

/tmp/ipykernel_3799/1271949873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_mean'].fillna(d['active_mean'].median(),inplace=True)

In [97]:
d['active_mean'].isnull().sum()

np.int64(0)

In [98]:
d['active_min'].fillna(d['active_min'].median(),inplace=True)

/tmp/ipykernel_3799/1982822974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_min'].fillna(d['active_min'].median(),inplace=True)

In [99]:
d['active_min'].isnull().sum()

np.int64(0)

In [100]:
d['active_std'].fillna(d['active_std'].median(),inplace=True)

/tmp/ipykernel_3799/1219665179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['active_std'].fillna(d['active_std'].median(),inplace=True)

In [101]:
d['active_std'].isnull().sum()

np.int64(0)

In [102]:
d['idle_std'].fillna(d['idle_std'].median(),inplace=True)

/tmp/ipykernel_3799/1919844647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_std'].fillna(d['idle_std'].median(),inplace=True)

In [103]:
d['idle_std'].isnull().sum()

np.int64(0)

In [104]:
d['idle_min'].fillna(d['idle_min'].median(),inplace=True)

/tmp/ipykernel_3799/1407437676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_min'].fillna(d['idle_min'].median(),inplace=True)

In [105]:
d['idle_mean'].fillna(d['idle_mean'].median(),inplace=True)

/tmp/ipykernel_3799/3194430402.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_mean'].fillna(d['idle_mean'].median(),inplace=True)

In [106]:
d['idle_max'].fillna(d['idle_max'].median(),inplace=True)

/tmp/ipykernel_3799/726970001.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['idle_max'].fillna(d['idle_max'].median(),inplace=True)

In [108]:
d['TnBPDstIP'].fillna(d['TnBPDstIP'].median(),inplace=True)

/tmp/ipykernel_3799/2836179091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnBPDstIP'].fillna(d['TnBPDstIP'].median(),inplace=True)

In [109]:
d['TnBPSrcIP'].fillna(d['TnBPSrcIP'].median(),inplace=True)

/tmp/ipykernel_3799/2770195538.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnBPSrcIP'].fillna(d['TnBPSrcIP'].median(),inplace=True)

In [110]:
d['TnPPDstIP'].fillna(d['TnPPDstIP'].median(),inplace=True)

/tmp/ipykernel_3799/3786267462.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPDstIP'].fillna(d['TnPPDstIP'].median(),inplace=True)

In [111]:
d['TnPPSrcIP'].fillna(d['TnPPSrcIP'].median(),inplace=True)

/tmp/ipykernel_3799/4003638087.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPSrcIP'].fillna(d['TnPPSrcIP'].median(),inplace=True)

In [112]:
d['TnPPerDport'].fillna(d['TnPPerDport'].median(),inplace=True)

/tmp/ipykernel_3799/3856550780.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['TnPPerDport'].fillna(d['TnPPerDport'].median(),inplace=True)

In [113]:
d['Tn_FlowsPDstIP'].fillna(d['Tn_FlowsPDstIP'].median(),inplace=True)

/tmp/ipykernel_3799/3052203981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Tn_FlowsPDstIP'].fillna(d['Tn_FlowsPDstIP'].median(),inplace=True)

In [116]:
d.isnull().sum()

flow_ID                  0
eth_type                 0
ip_proto                 0
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Attack                   2
Category                 0
dtype: int64

In [115]:
d['Tn_FlowsPSrcIP'].fillna(d['Tn_FlowsPSrcIP'].median(),inplace=True)

/tmp/ipykernel_3799/3089895386.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Tn_FlowsPSrcIP'].fillna(d['Tn_FlowsPSrcIP'].median(),inplace=True)

In [129]:
X=d.drop(columns='Attack',axis=1)
Y=d['Attack']

In [130]:
X

,flow_ID,eth_type,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,...,idle_min,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Category
0,126363,2048,6,53068.0,3000.0,1.151,684.0,4.0,594.265856,3.475239,...,0.0,0.0,127644.0,127644.0,853.0,853.0,853.0,205.0,205.0,7
1,37855,2048,6,8180.0,3300.0,7.353,120.0,2.0,16.319869,0.271998,...,6.0,0.0,120.0,10620.0,2.0,177.0,2.0,1.0,94.0,6
2,40477,2048,6,443.0,41444.0,0.210,78.0,1.0,371.428571,4.761905,...,0.0,0.0,299516014.0,78.0,254012.0,1.0,1.0,154.0,1.0,2
3,125944,2048,6,50282.0,3000.0,6.695,544.0,4.0,81.254668,0.597461,...,2.0,0.0,133860.0,133860.0,922.0,922.0,922.0,212.0,212.0,7
4,122609,2048,6,54504.0,80.0,1.456,601.0,4.0,412.774725,2.747253,...,0.0,0.0,181923.0,181923.0,1109.0,1109.0,1109.0,258.0,258.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352421,119880,2048,6,443.0,35420.0,5.175,148.0,2.0,28.599034,0.386473,...,2.0,0.0,65276113.0,7517.0,55428.0,15.0,2.0,72.0,2.0,2
352422,83488,2048,6,80.0,58154.0,3.980,743.0,4.0,186.683417,1.005025,...,0.0,0.0,138399.0,138399.0,752.0,752.0,4.0,185.0,185.0,7
352423,131933,2048,17,60673.0,53.0,0.339,0.0,0.0,0.000000,0.000000,...,0.0,0.0,24168.0,55764.0,121.0,299.0,2.0,8.0,42.0,0
352424,146868,2048,6,80.0,37238.0,0.360,0.0,0.0,0.000000,0.000000,...,0.0,0.0,64637855.0,5396.0,54547.0,18.0,0.0,24.0,4.0,2
352425,121959,2048,17,53.0,43210.0,2.304,0.0,0.0,0.000000,0.000000,...,0.0,0.0,109393585.0,269.0,92415.0,2.0,0.0,43.0,18.0,0

In [131]:
Y

0         1.0
1         1.0
2         0.0
3         1.0
4         1.0
         ...
352421    0.0
352422    1.0
352423    0.0
352424    0.0
352425    0.0
Name: Attack, Length: 352426, dtype: float64

In [120]:
Y.isnull().sum()

np.int64(2)

In [125]:
Y.isnull().sum()

np.int64(0)

In [134]:
Y.median()

1.0

In [136]:
Y.fillna(Y.median(),inplace=True)

In [137]:
Y

0         1.0
1         1.0
2         0.0
3         1.0
4         1.0
         ...
352421    0.0
352422    1.0
352423    0.0
352424    0.0
352425    0.0
Name: Attack, Length: 352426, dtype: float64

In [138]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [139]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [140]:
X_train

array([[-1.12406758,  0.00729422, -0.32584887, ...,  2.19809216,
        -1.03198382,  0.73531619],
       [ 0.80271417,  0.00729422, -0.32584887, ...,  0.11970021,
         0.12096274,  1.11688839],
       [-1.66929339,  0.00729422, -0.32584887, ...,  1.54746512,
        -1.03198382,  0.73531619],
       ...,
       [ 0.41717694,  0.00729422, -0.32584887, ...,  0.57152455,
         0.59738694,  1.11688839],
       [-1.02562376,  0.00729422, -0.32584887, ..., -0.97371468,
         0.10190577,  0.73531619],
       [ 1.36970498,  0.00729422, -0.32584887, ...,  1.74626783,
         1.83608985,  1.11688839]])

In [141]:
X_test

array([[ 0.54544686,  0.00729422, -0.32584887, ...,  0.51730563,
         0.54021604,  1.11688839],
       [ 0.66903741,  0.00729422, -0.32584887, ...,  1.27637052,
         1.34060869,  1.11688839],
       [ 1.10915424,  0.00729422, -0.32584887, ..., -0.52189035,
        -1.02245533, -0.79097262],
       ...,
       [-0.36966584,  0.00729422, -1.56851193, ..., -0.97371468,
         0.67361481,  0.73531619],
       [-0.56146123,  0.00729422, -1.56851193, ..., -0.97371468,
         0.18766213,  0.73531619],
       [ 0.00342583,  0.00729422, -0.32584887, ...,  0.73418131,
         0.76889965,  1.11688839]])

In [142]:
Y_train

95795     1.0
262454    1.0
225412    1.0
313558    1.0
74216     0.0
         ...
84434     1.0
95816     0.0
203245    1.0
100879    1.0
351400    1.0
Name: Attack, Length: 281940, dtype: float64

In [143]:
Y_test

264454    1.0
23563     1.0
298690    0.0
264757    0.0
197613    1.0
         ...
320856    0.0
7544      0.0
278763    1.0
82723     1.0
64028     1.0
Name: Attack, Length: 70486, dtype: float64

In [150]:
from sklearn.linear_model import LogisticRegression

In [152]:
model=LogisticRegression()

In [153]:
model.fit(X_train,Y_train)

LogisticRegression()

In [154]:
model

LogisticRegression()

In [155]:
Y_pred=model.predict(X_test)

In [156]:
from sklearn.metrics import accuracy_score

In [157]:
accuracy_score(Y_test,Y_pred)

0.9999290639275884

In [158]:
Y.value_counts()

Attack
1.0    176736
0.0    175690
Name: count, dtype: int64

In [160]:
from sklearn.ensemble import RandomForestClassifier

In [162]:
import xgboost as xgb

In [163]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[35218,     5],
       [    0, 35263]])