<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
d=pd.read_csv('Train_ULAK.csv')

In [ ]:
d.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,68855579,10,6,1038,11595,346,0,103.800000,167.133879,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,53,196,2,2,70,174,35,35,35.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,123,118,2,2,96,96,48,48,48.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,80,295657,7,10,1114,15841,1084,0,159.142857,407.829796,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,80,15705351,7,5,407,452,377,0,58.142857,140.620563,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [ ]:
d.drop(columns=' Destination Port',inplace=True)

In [ ]:
d.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,...,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,196,2,2,70,174,35,35,35.000000,0.000000,87,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,118,2,2,96,96,48,48,48.000000,0.000000,48,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,...,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [ ]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
d.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000,2,602465,1.204930e+05,1.934046e+05,444104,49,0,0,0,0,328,200,0.145232,0.087139,0,4344,743.117647,1341.078106,1.798490e+06,0,0,0,0,1,0,0,0,0,789.562500,103.800000,1932.5,328,0,0,0,0,0,0,10,1038,6,11595,251,235,3,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,DoS Hulk
1,196,2,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3,3,3,3.000000e+00,0.000000e+00,3,3,0,0,0,0,64,64,10204.081630,10204.081630,35,87,55.800000,28.481573,8.112000e+02,0,0,0,0,0,0,0,0,1,69.750000,35.000000,87.0,64,0,0,0,0,0,0,2,70,2,174,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,118,2,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3,3,4,4.000000e+00,0.000000e+00,4,4,0,0,0,0,40,40,16949.152540,16949.152540,48,48,48.000000,0.000000,0.000000e+00,0,0,0,0,0,0,0,0,1,60.000000,48.000000,48.0,40,0,0,0,0,0,0,2,96,2,96,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299,192,262576,2.917511e+04,8.701429e+04,261213,2,0,0,0,0,152,208,23.676084,33.822977,0,2920,941.944444,968.551646,9.380923e+05,0,0,0,1,0,0,0,0,1,997.352941,159.142857,1584.1,152,0,0,0,0,0,0,7,1114,10,15841,8192,11,6,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208,375,10100000,2.532037e+06,4.846203e+06,9799947,1261,0,0,0,0,152,108,0.445708,0.318363,0,377,66.076923,123.295351,1.520174e+04,0,0,0,1,0,0,0,0,0,71.583333,58.142857,90.4,152,0,0,0,0,0,0,7,407,5,452,8192,16384,6,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,BENIGN

In [ ]:
d.dtypes

 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
 Total Length of Bwd Packets      int64
 Fwd Packet Length Max            int64
 Fwd Packet Length Min            int64
 Fwd Packet Length Mean         float64
 Fwd Packet Length Std          float64
Bwd Packet Length Max             int64
 Bwd Packet Length Min            int64
 Bwd Packet Length Mean         float64
 Bwd Packet Length Std          float64
Flow Bytes/s                    float64
 Flow Packets/s                 float64
 Flow IAT Mean                  float64
 Flow IAT Std                   float64
 Flow IAT Max                     int64
 Flow IAT Min                     int64
Fwd IAT Total                     int64
 Fwd IAT Mean                   float64
 Fwd IAT Std                    float64
 Fwd IAT Max                      int64
 Fwd IAT Min                      int64
Bwd IAT Total                     int64
 Bwd IAT Mean                   float64
 Bwd IAT Std                    float64
 Bwd IAT Max                      int64
 Bwd IAT Min                      int64
Fwd PSH Flags                     int64
 Bwd PSH Flags                    int64
 Fwd URG Flags                    int64
 Bwd URG Flags                    int64
 Fwd Header Length                int64
 Bwd Header Length                int64
Fwd Packets/s                   float64
 Bwd Packets/s                  float64
 Min Packet Length                int64
 Max Packet Length                int64
 Packet Length Mean             float64
 Packet Length Std              float64
 Packet Length Variance         float64
FIN Flag Count                    int64
 SYN Flag Count                   int64
 RST Flag Count                   int64
 PSH Flag Count                   int64
 ACK Flag Count                   int64
 URG Flag Count                   int64
 CWE Flag Count                   int64
 ECE Flag Count                   int64
 Down/Up Ratio                    int64
 Average Packet Size            float64
 Avg Fwd Segment Size           float64
 Avg Bwd Segment Size           float64
 Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk                int64
 Fwd Avg Packets/Bulk             int64
 Fwd Avg Bulk Rate                int64
 Bwd Avg Bytes/Bulk               int64
 Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                 int64
Subflow Fwd Packets               int64
 Subflow Fwd Bytes                int64
 Subflow Bwd Packets              int64
 Subflow Bwd Bytes                int64
Init_Win_bytes_forward            int64
 Init_Win_bytes_backward          int64
 act_data_pkt_fwd                 int64
 min_seg_size_forward             int64
Active Mean                     float64
 Active Std                     float64
 Active Max                       int64
 Active Min                       int64
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                         int64
 Idle Min                         int64
 Label                           object
dtype: object

In [ ]:
labelencoder=LabelEncoder()

In [ ]:
target=labelencoder.fit_transform(d[' Label'])

In [ ]:
d[' Label']=target

In [ ]:
d.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000,2,602465,1.204930e+05,1.934046e+05,444104,49,0,0,0,0,328,200,0.145232,0.087139,0,4344,743.117647,1341.078106,1.798490e+06,0,0,0,0,1,0,0,0,0,789.562500,103.800000,1932.5,328,0,0,0,0,0,0,10,1038,6,11595,251,235,3,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,4
1,196,2,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3,3,3,3.000000e+00,0.000000e+00,3,3,0,0,0,0,64,64,10204.081630,10204.081630,35,87,55.800000,28.481573,8.112000e+02,0,0,0,0,0,0,0,0,1,69.750000,35.000000,87.0,64,0,0,0,0,0,0,2,70,2,174,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,0
2,118,2,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3,3,4,4.000000e+00,0.000000e+00,4,4,0,0,0,0,40,40,16949.152540,16949.152540,48,48,48.000000,0.000000,0.000000e+00,0,0,0,0,0,0,0,0,1,60.000000,48.000000,48.0,40,0,0,0,0,0,0,2,96,2,96,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299,192,262576,2.917511e+04,8.701429e+04,261213,2,0,0,0,0,152,208,23.676084,33.822977,0,2920,941.944444,968.551646,9.380923e+05,0,0,0,1,0,0,0,0,1,997.352941,159.142857,1584.1,152,0,0,0,0,0,0,7,1114,10,15841,8192,11,6,20,0.0,0.0,0,0,0.0,0.0,0,0,0
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208,375,10100000,2.532037e+06,4.846203e+06,9799947,1261,0,0,0,0,152,108,0.445708,0.318363,0,377,66.076923,123.295351,1.520174e+04,0,0,0,1,0,0,0,0,0,71.583333,58.142857,90.4,152,0,0,0,0,0,0,7,407,5,452,8192,16384,6,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,0

In [ ]:
scaler=StandardScaler()

In [ ]:
np.isinf(d).sum()

 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    385
 Flow Packets/s                 725
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
 Label                            0
dtype: int64

In [ ]:
d=d.replace([np.inf,-np.inf],0)

In [ ]:
np.isinf(d).sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
 Fwd Packet Length Max          0
 Fwd Packet Length Min          0
 Fwd Packet Length Mean         0
 Fwd Packet Length Std          0
Bwd Packet Length Max           0
 Bwd Packet Length Min          0
 Bwd Packet Length Mean         0
 Bwd Packet Length Std          0
Flow Bytes/s                    0
 Flow Packets/s                 0
 Flow IAT Mean                  0
 Flow IAT Std                   0
 Flow IAT Max                   0
 Flow IAT Min                   0
Fwd IAT Total                   0
 Fwd IAT Mean                   0
 Fwd IAT Std                    0
 Fwd IAT Max                    0
 Fwd IAT Min                    0
Bwd IAT Total                   0
 Bwd IAT Mean                   0
 Bwd IAT Std                    0
 Bwd IAT Max                    0
 Bwd IAT Min                    0
Fwd PSH Flags                   0
 Bwd PSH Flags                  0
 Fwd URG Flags                  0
 Bwd URG Flags                  0
 Fwd Header Length              0
 Bwd Header Length              0
Fwd Packets/s                   0
 Bwd Packets/s                  0
 Min Packet Length              0
 Max Packet Length              0
 Packet Length Mean             0
 Packet Length Std              0
 Packet Length Variance         0
FIN Flag Count                  0
 SYN Flag Count                 0
 RST Flag Count                 0
 PSH Flag Count                 0
 ACK Flag Count                 0
 URG Flag Count                 0
 CWE Flag Count                 0
 ECE Flag Count                 0
 Down/Up Ratio                  0
 Average Packet Size            0
 Avg Fwd Segment Size           0
 Avg Bwd Segment Size           0
 Fwd Header Length.1            0
Fwd Avg Bytes/Bulk              0
 Fwd Avg Packets/Bulk           0
 Fwd Avg Bulk Rate              0
 Bwd Avg Bytes/Bulk             0
 Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
 Subflow Fwd Bytes              0
 Subflow Bwd Packets            0
 Subflow Bwd Bytes              0
Init_Win_bytes_forward          0
 Init_Win_bytes_backward        0
 act_data_pkt_fwd               0
 min_seg_size_forward           0
Active Mean                     0
 Active Std                     0
 Active Max                     0
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
 Label                          0
dtype: int64

In [ ]:
Y=target

In [ ]:
X=d

In [ ]:
X.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000,2,602465,1.204930e+05,1.934046e+05,444104,49,0,0,0,0,328,200,0.145232,0.087139,0,4344,743.117647,1341.078106,1.798490e+06,0,0,0,0,1,0,0,0,0,789.562500,103.800000,1932.5,328,0,0,0,0,0,0,10,1038,6,11595,251,235,3,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000,4
1,196,2,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3,3,3,3.000000e+00,0.000000e+00,3,3,0,0,0,0,64,64,10204.081630,10204.081630,35,87,55.800000,28.481573,8.112000e+02,0,0,0,0,0,0,0,0,1,69.750000,35.000000,87.0,64,0,0,0,0,0,0,2,70,2,174,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,0
2,118,2,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3,3,4,4.000000e+00,0.000000e+00,4,4,0,0,0,0,40,40,16949.152540,16949.152540,48,48,48.000000,0.000000,0.000000e+00,0,0,0,0,0,0,0,0,1,60.000000,48.000000,48.0,40,0,0,0,0,0,0,2,96,2,96,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299,192,262576,2.917511e+04,8.701429e+04,261213,2,0,0,0,0,152,208,23.676084,33.822977,0,2920,941.944444,968.551646,9.380923e+05,0,0,0,1,0,0,0,0,1,997.352941,159.142857,1584.1,152,0,0,0,0,0,0,7,1114,10,15841,8192,11,6,20,0.0,0.0,0,0,0.0,0.0,0,0,0
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208,375,10100000,2.532037e+06,4.846203e+06,9799947,1261,0,0,0,0,152,108,0.445708,0.318363,0,377,66.076923,123.295351,1.520174e+04,0,0,0,1,0,0,0,0,0,71.583333,58.142857,90.4,152,0,0,0,0,0,0,7,407,5,452,8192,16384,6,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208,0

In [ ]:
X=X.drop(columns=' Label')

In [ ]:
X.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,68855579,10,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000,2,602465,1.204930e+05,1.934046e+05,444104,49,0,0,0,0,328,200,0.145232,0.087139,0,4344,743.117647,1341.078106,1.798490e+06,0,0,0,0,1,0,0,0,0,789.562500,103.800000,1932.5,328,0,0,0,0,0,0,10,1038,6,11595,251,235,3,32,998.0,0.0,998,998,68300000.0,0.0,68300000,68300000
1,196,2,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3,3,3,3.000000e+00,0.000000e+00,3,3,0,0,0,0,64,64,10204.081630,10204.081630,35,87,55.800000,28.481573,8.112000e+02,0,0,0,0,0,0,0,0,1,69.750000,35.000000,87.0,64,0,0,0,0,0,0,2,70,2,174,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0
2,118,2,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3,3,4,4.000000e+00,0.000000e+00,4,4,0,0,0,0,40,40,16949.152540,16949.152540,48,48,48.000000,0.000000,0.000000e+00,0,0,0,0,0,0,0,0,1,60.000000,48.000000,48.0,40,0,0,0,0,0,0,2,96,2,96,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0
3,295657,7,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299,192,262576,2.917511e+04,8.701429e+04,261213,2,0,0,0,0,152,208,23.676084,33.822977,0,2920,941.944444,968.551646,9.380923e+05,0,0,0,1,0,0,0,0,1,997.352941,159.142857,1584.1,152,0,0,0,0,0,0,7,1114,10,15841,8192,11,6,20,0.0,0.0,0,0,0.0,0.0,0,0
4,15705351,7,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208,375,10100000,2.532037e+06,4.846203e+06,9799947,1261,0,0,0,0,152,108,0.445708,0.318363,0,377,66.076923,123.295351,1.520174e+04,0,0,0,1,0,0,0,0,0,71.583333,58.142857,90.4,152,0,0,0,0,0,0,7,407,5,452,8192,16384,6,20,360718.0,0.0,360718,360718,9767208.0,0.0,9767208,9767208

In [ ]:
Y

array([4, 0, 0, ..., 3, 0, 0])

In [ ]:
scaler

StandardScaler()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [ ]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[ 3.11500494e+00,  8.94273563e-02,  1.16321933e-01, ...,
         1.56295445e-01,  2.04511444e+00,  2.09154939e+00],
       [-4.39119828e-01, -1.18440519e-02, -1.00080020e-02, ...,
        -1.10482032e-01, -3.56606584e-01, -3.38386579e-01],
       [-4.39120125e-01, -1.04176940e-02, -8.93740934e-03, ...,
        -1.10482032e-01, -3.56606584e-01, -3.38386579e-01],
       ...,
       [-4.39120601e-01, -1.18440519e-02, -1.00080020e-02, ...,
        -1.10482032e-01, -3.56606584e-01, -3.38386579e-01],
       [-2.62736334e-01,  5.27224245e-03,  1.76851734e-03, ...,
        -1.10482032e-01, -1.30642899e-01, -1.02510594e-01],
       [-4.39117065e-01, -1.04176940e-02, -8.93740934e-03, ...,
        -1.10482032e-01, -3.56606584e-01, -3.38386579e-01]])

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb=XGBClassifier()

In [ ]:
estimators=[('xgb',xgb)]

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe=Pipeline(steps=estimators)

In [ ]:
!pip install scikit_optimize

Collecting scikit_optimize
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.5.3)
Collecting pyaml>=16.9 (from scikit_optimize)
  Downloading pyaml-26.2.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (26.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit_optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit_optimize) (3.6.0)
Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 6.7 MB/s eta 0:00:00
Downloading pyaml-26.2.1-py3-none-any.whl (27 kB)
Installing collected packages: pyaml, scikit_optimize
Successfully installed pyaml-26.2.1 scikit_optimize-0.10.2

In [ ]:
from skopt import BayesSearchCV

In [ ]:
from skopt.space import Real,Categorical,Integer

In [ ]:
search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [ ]:
opt=BayesSearchCV(pipe,search_space,n_iter=100,cv=2,scoring='roc_auc',random_state=8)

In [ ]:
opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=2
)

In [ ]:
q=pd.DataFrame(Y)

In [ ]:
q.value_counts()

0
0     581639
4      58790
10     40800
2      32679
3       2635
7       1988
11      1558
6       1481
5       1398
1        487
12       382
14       178
9          9
13         6
8          1
Name: count, dtype: int64

In [ ]:
q=q[q!=8]

In [ ]:
q=q[q!=9]

In [ ]:
q=q[q!=13]

In [ ]:
q.value_counts()

0
0.0     581639
4.0      58790
10.0     40800
2.0      32679
3.0       2635
7.0       1988
11.0      1558
6.0       1481
5.0       1398
1.0        487
12.0       382
14.0       178
Name: count, dtype: int64

In [ ]:
Y=q

In [ ]:
X_train.shape

(579224, 77)

In [ ]:
X_test.shape

(144807, 77)

In [ ]:
q.fillna(0,inplace=True)

In [ ]:
Y_train=q

In [ ]:
Y_train.shape

(724031, 1)

In [ ]:
Y_train.dtypes

0    float64
dtype: object

In [ ]:
Y_train.value_counts()

0
0.0     581655
4.0      58790
10.0     40800
2.0      32679
3.0       2635
7.0       1988
11.0      1558
6.0       1481
5.0       1398
1.0        487
12.0       382
14.0       178
Name: count, dtype: int64

In [ ]:
Y_train=labelencoder.fit_transform(Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
Y_train.shape

(724031,)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder=LabelEncoder()

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [ ]:
X_train.shape

(579224, 77)

In [ ]:
Y_train.shape

(579224, 1)

In [ ]:
X_train.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
297225,119609957,72,119,7356,111862,931,0,102.166667,225.384429,2860,0,940.016807,702.156774,996.72304,1.596857,629526.089500,5.891998e+06,58500000,1,120000000,1684136.662,9597881.543,58500000,76,120000000,1013334.847,7467280.454,58500000,1,0,0,0,0,1452,2392,0.601957,0.99490,0,2860,620.927083,700.267447,490374.497300,0,0,0,1,0,0,0,0,1,624.178011,102.166667,940.016807,1452,0,0,0,0,0,0,72,7356,119,111862,8192,489,71,20,1622919.5,586456.6866,2037607,1208232,57600000.0,1240792.089,58500000,56700000
418993,69,1,1,0,6,0,0,0.000000,0.000000,6,6,6.000000,0.000000,86956.52174,28985.507250,69.000000,0.000000e+00,69,69,0,0.000,0.000,0,0,0,0.000,0.000,0,0,0,0,0,0,40,20,14492.753620,14492.75362,0,6,2.000000,3.464102,12.000000,0,0,0,1,0,0,0,0,1,3.000000,0.000000,6.000000,40,0,0,0,0,0,0,1,0,1,6,29200,0,0,40,0.0,0.0000,0,0,0.0,0.000,0,0
23025,59,2,2,4,12,2,2,2.000000,0.000000,6,6,6.000000,0.000000,271186.44070,67796.610170,19.666667,2.478575e+01,48,2,2,2.000,0.000,2,2,48,48.000,0.000,48,48,0,0,0,0,48,40,33898.305080,33898.30508,2,6,3.600000,2.190890,4.800000,0,0,0,1,0,0,0,0,1,4.500000,2.000000,6.000000,48,0,0,0,0,0,0,2,4,2,12,1024,0,1,24,0.0,0.0000,0,0,0.0,0.000,0,0
435744,43,1,1,2,6,2,2,2.000000,0.000000,6,6,6.000000,0.000000,186046.51160,46511.627910,43.000000,0.000000e+00,43,43,0,0.000,0.000,0,0,0,0.000,0.000,0,0,0,0,0,0,24,20,23255.813950,23255.81395,2,6,3.333333,2.309401,5.333333,0,0,0,1,0,0,0,0,1,5.000000,2.000000,6.000000,24,0,0,0,0,0,0,1,2,1,6,1024,0,0,24,0.0,0.0000,0,0,0.0,0.000,0,0
588430,1172,2,0,12,0,6,6,6.000000,0.000000,0,0,0.000000,0.000000,10238.90785,1706.484642,1172.000000,0.000000e+00,1172,1172,1172,1172.000,0.000,1172,1172,0,0.000,0.000,0,0,0,0,0,0,40,0,1706.484642,0.00000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,0,9.000000,6.000000,0.000000,40,0,0,0,0,0,0,2,12,0,0,131,-1,1,20,0.0,0.0000,0,0,0.0,0.000,0,0

In [ ]:
Y_train.head()

           0
297225   0.0
418993  10.0
23025    0.0
435744  10.0
588430   0.0

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb=XGBClassifier()

In [ ]:
estimators=[('xgb',xgb)]

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe=Pipeline(steps=estimators)

In [ ]:
!pip install scikit_optimize

Requirement already satisfied: scikit_optimize in /usr/local/lib/python3.12/dist-packages (0.10.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.5.3)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (26.2.1)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit_optimize) (26.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit_optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit_optimize) (3.6.0)

In [ ]:
from skopt import BayesSearchCV

In [ ]:
from skopt.space import Real,Categorical,Integer

In [ ]:
search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [ ]:
opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=2,scoring='roc_auc',random_state=8)

In [ ]:
opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=2)

In [ ]:
Y_train.shape

(579224, 1)

In [ ]:
X_train.shape

(579224, 77)

In [ ]:
Y_train=labelencoder.fit_transform(Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
Y_train.head()

           0
297225   0.0
418993  10.0
23025    0.0
435744  10.0
588430   0.0

In [ ]:
Y_train=labelencoder.fit_transform(Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
w=Y_train

In [ ]:
w=pd.DataFrame(Y_train)

In [ ]:
w.value_counts()

0
0     465271
4      47065
8      32607
2      26196
3       2118
7       1575
9       1247
6       1193
5       1116
1        380
10       307
11       149
Name: count, dtype: int64

In [ ]:
Y_train=w.to_numpy()

In [ ]:
opt.fit(X_train,Y_train)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.metrics import classification_report

# Predictions
y_pred = opt.predict(X_test)

# Classification report
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    116384
         1.0       0.92      0.73      0.81       107
         2.0       1.00      1.00      1.00      6483
         3.0       1.00      1.00      1.00       517
         4.0       1.00      1.00      1.00     11725
         5.0       0.95      0.99      0.97       282
         6.0       1.00      0.99      1.00       288
         7.0       1.00      1.00      1.00       413
         8.0       0.00      0.00      0.00         0
         9.0       0.00      0.00      0.00         0
        10.0       0.00      0.00      0.00      8193
        11.0       0.00      0.00      0.00       311
        12.0       0.00      0.00      0.00        75
        14.0       0.00      0.00      0.00        29

    accuracy                           0.94    144807
   macro avg       0.56      0.55      0.56    144807
weighted avg       0.94      0.94      0.94    144807

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
accuracy_score(Y_test,y_pred)

0.939498781136271

In [ ]:
test=pd.read_csv('Test_ULAK.csv')

In [ ]:
test.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,998,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,2004.008016,9.980000e+02,0.000000e+00,998,998,998,998.0,0.0,998,998,0,0.0,0.0,0,0,0,0,0,0,64,0,2004.008016,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,251.0,-1.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DoS Hulk
1,80,63111103,7,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,0.110916,1.050000e+07,1.190000e+07,32100000,999612,63100000,10500000.0,11900000.0,32100000,999612,0,0.0,0.0,0,0,0,0,0,0,280,0,0.110916,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,280.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,29200.0,-1.0,0.0,40.0,7015565.0,0.0,7015565.0,7015565.0,18700000.0,12200000.0,32100000.0,8015910.0,DoS Slowhttptest
2,53,202,2,2,98,130,49,49,49.0,0.0,65,65,65.0,0.0,1.128713e+06,19801.980200,6.733333e+01,3.348632e+01,106,48,48,48.0,0.0,48,48,48,48.0,0.0,48,48,0,0,0,0,40,40,9900.990099,9900.990099,49,65,55.4,8.763561,76.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.25,49.0,65.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,98.0,2.0,130.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,80,3,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,666666.666700,3.000000e+00,0.000000e+00,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,64,0,666666.666700,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,274.0,-1.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DoS Hulk
4,7200,37,1,1,0,6,0,0,0.0,0.0,6,6,6.0,0.0,1.621622e+05,54054.054050,3.700000e+01,0.000000e+00,37,37,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,40,20,27027.027030,27027.027030,0,6,2.0,3.464102,12.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.00,0.0,6.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,6.0,29200.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,PortScan

In [ ]:
test.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,998,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,2004.008016,9.980000e+02,0.000000e+00,998,998,998,998.0,0.0,998,998,0,0.0,0.0,0,0,0,0,0,0,64,0,2004.008016,0.000000,0,0,0.0,0.000000,0.0,0,0,0,0,1,0,0,0,0,0.00,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,251,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,4
1,63111103,7,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,0.110916,1.050000e+07,1.190000e+07,32100000,999612,63100000,10500000.0,11900000.0,32100000,999612,0,0.0,0.0,0,0,0,0,0,0,280,0,0.110916,0.000000,0,0,0.0,0.000000,0.0,0,0,0,1,0,0,0,0,0,0.00,0.0,0.0,280,0,0,0,0,0,0,7,0,0,0,29200,-1,0,40,7015565.0,0.0,7015565,7015565,18700000.0,12200000.0,32100000,8015910,5
2,202,2,2,98,130,49,49,49.0,0.0,65,65,65.0,0.0,1.128713e+06,19801.980200,6.733333e+01,3.348632e+01,106,48,48,48.0,0.0,48,48,48,48.0,0.0,48,48,0,0,0,0,40,40,9900.990099,9900.990099,49,65,55.4,8.763561,76.8,0,0,0,0,0,0,0,0,1,69.25,49.0,65.0,40,0,0,0,0,0,0,2,98,2,130,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,3,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,666666.666700,3.000000e+00,0.000000e+00,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,64,0,666666.666700,0.000000,0,0,0.0,0.000000,0.0,0,0,0,0,1,0,0,0,0,0.00,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,274,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,4
4,37,1,1,0,6,0,0,0.0,0.0,6,6,6.0,0.0,1.621622e+05,54054.054050,3.700000e+01,0.000000e+00,37,37,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,40,20,27027.027030,27027.027030,0,6,2.0,3.464102,12.0,0,0,0,1,0,0,0,0,1,3.00,0.0,6.0,40,0,0,0,0,0,0,1,0,1,6,29200,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0,10

In [ ]:
test.drop(columns=' Destination Port',inplace=True)

In [ ]:
target=labelencoder.fit_transform(test[' Label'])

In [ ]:
test[' Label']=target

In [ ]:
test.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,998,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,2004.008016,9.980000e+02,0.000000e+00,998,998,998,998.0,0.0,998,998,0,0.0,0.0,0,0,0,0,0,0,64,0,2004.008016,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,251.0,-1.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
1,63111103,7,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,0.110916,1.050000e+07,1.190000e+07,32100000,999612,63100000,10500000.0,11900000.0,32100000,999612,0,0.0,0.0,0,0,0,0,0,0,280,0,0.110916,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,280.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,29200.0,-1.0,0.0,40.0,7015565.0,0.0,7015565.0,7015565.0,18700000.0,12200000.0,32100000.0,8015910.0,5
2,202,2,2,98,130,49,49,49.0,0.0,65,65,65.0,0.0,1.128713e+06,19801.980200,6.733333e+01,3.348632e+01,106,48,48,48.0,0.0,48,48,48,48.0,0.0,48,48,0,0,0,0,40,40,9900.990099,9900.990099,49,65,55.4,8.763561,76.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.25,49.0,65.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,98.0,2.0,130.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,3,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,666666.666700,3.000000e+00,0.000000e+00,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,64,0,666666.666700,0.000000,0,0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,274.0,-1.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,37,1,1,0,6,0,0,0.0,0.0,6,6,6.0,0.0,1.621622e+05,54054.054050,3.700000e+01,0.000000e+00,37,37,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,40,20,27027.027030,27027.027030,0,6,2.0,3.464102,12.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.00,0.0,6.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,6.0,29200.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9

In [ ]:
target

array([ 4,  5,  0, ...,  0,  0, 14])

In [ ]:
Xt=test
Yt=target

In [ ]:
np.isinf(Xt).sum()

 Flow Duration                   0
 Total Fwd Packets               0
 Total Backward Packets          0
Total Length of Fwd Packets      0
 Total Length of Bwd Packets     0
 Fwd Packet Length Max           0
 Fwd Packet Length Min           0
 Fwd Packet Length Mean          0
 Fwd Packet Length Std           0
Bwd Packet Length Max            0
 Bwd Packet Length Min           0
 Bwd Packet Length Mean          0
 Bwd Packet Length Std           0
Flow Bytes/s                    43
 Flow Packets/s                 74
 Flow IAT Mean                   0
 Flow IAT Std                    0
 Flow IAT Max                    0
 Flow IAT Min                    0
Fwd IAT Total                    0
 Fwd IAT Mean                    0
 Fwd IAT Std                     0
 Fwd IAT Max                     0
 Fwd IAT Min                     0
Bwd IAT Total                    0
 Bwd IAT Mean                    0
 Bwd IAT Std                     0
 Bwd IAT Max                     0
 Bwd IAT Min                     0
Fwd PSH Flags                    0
 Bwd PSH Flags                   0
 Fwd URG Flags                   0
 Bwd URG Flags                   0
 Fwd Header Length               0
 Bwd Header Length               0
Fwd Packets/s                    0
 Bwd Packets/s                   0
 Min Packet Length               0
 Max Packet Length               0
 Packet Length Mean              0
 Packet Length Std               0
 Packet Length Variance          0
FIN Flag Count                   0
 SYN Flag Count                  0
 RST Flag Count                  0
 PSH Flag Count                  0
 ACK Flag Count                  0
 URG Flag Count                  0
 CWE Flag Count                  0
 ECE Flag Count                  0
 Down/Up Ratio                   0
 Average Packet Size             0
 Avg Fwd Segment Size            0
 Avg Bwd Segment Size            0
 Fwd Header Length.1             0
Fwd Avg Bytes/Bulk               0
 Fwd Avg Packets/Bulk            0
 Fwd Avg Bulk Rate               0
 Bwd Avg Bytes/Bulk              0
 Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
 Subflow Fwd Bytes               0
 Subflow Bwd Packets             0
 Subflow Bwd Bytes               0
Init_Win_bytes_forward           0
 Init_Win_bytes_backward         0
 act_data_pkt_fwd                0
 min_seg_size_forward            0
Active Mean                      0
 Active Std                      0
 Active Max                      0
 Active Min                      0
Idle Mean                        0
 Idle Std                        0
 Idle Max                        0
 Idle Min                        0
 Label                           0
dtype: int64

In [ ]:
np.isinf(Yt).sum()

np.int64(0)

In [ ]:
Xt.replace([np.inf,-np.inf],0,inplace=True)

In [ ]:
np.isinf(Xt).sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
 Fwd Packet Length Max          0
 Fwd Packet Length Min          0
 Fwd Packet Length Mean         0
 Fwd Packet Length Std          0
Bwd Packet Length Max           0
 Bwd Packet Length Min          0
 Bwd Packet Length Mean         0
 Bwd Packet Length Std          0
Flow Bytes/s                    0
 Flow Packets/s                 0
 Flow IAT Mean                  0
 Flow IAT Std                   0
 Flow IAT Max                   0
 Flow IAT Min                   0
Fwd IAT Total                   0
 Fwd IAT Mean                   0
 Fwd IAT Std                    0
 Fwd IAT Max                    0
 Fwd IAT Min                    0
Bwd IAT Total                   0
 Bwd IAT Mean                   0
 Bwd IAT Std                    0
 Bwd IAT Max                    0
 Bwd IAT Min                    0
Fwd PSH Flags                   0
 Bwd PSH Flags                  0
 Fwd URG Flags                  0
 Bwd URG Flags                  0
 Fwd Header Length              0
 Bwd Header Length              0
Fwd Packets/s                   0
 Bwd Packets/s                  0
 Min Packet Length              0
 Max Packet Length              0
 Packet Length Mean             0
 Packet Length Std              0
 Packet Length Variance         0
FIN Flag Count                  0
 SYN Flag Count                 0
 RST Flag Count                 0
 PSH Flag Count                 0
 ACK Flag Count                 0
 URG Flag Count                 0
 CWE Flag Count                 0
 ECE Flag Count                 0
 Down/Up Ratio                  0
 Average Packet Size            0
 Avg Fwd Segment Size           0
 Avg Bwd Segment Size           0
 Fwd Header Length.1            0
Fwd Avg Bytes/Bulk              0
 Fwd Avg Packets/Bulk           0
 Fwd Avg Bulk Rate              0
 Bwd Avg Bytes/Bulk             0
 Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
 Subflow Fwd Bytes              0
 Subflow Bwd Packets            0
 Subflow Bwd Bytes              0
Init_Win_bytes_forward          0
 Init_Win_bytes_backward        0
 act_data_pkt_fwd               0
 min_seg_size_forward           0
Active Mean                     0
 Active Std                     0
 Active Max                     0
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
dtype: int64

In [152]:
Xt.isnull().sum()

AttributeError: 'NoneType' object has no attribute 'isnull'

In [ ]:
Xt.fillna(0,inplace=True)

In [ ]:
Xt.isnull().sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
 Fwd Packet Length Max          0
 Fwd Packet Length Min          0
 Fwd Packet Length Mean         0
 Fwd Packet Length Std          0
Bwd Packet Length Max           0
 Bwd Packet Length Min          0
 Bwd Packet Length Mean         0
 Bwd Packet Length Std          0
Flow Bytes/s                    0
 Flow Packets/s                 0
 Flow IAT Mean                  0
 Flow IAT Std                   0
 Flow IAT Max                   0
 Flow IAT Min                   0
Fwd IAT Total                   0
 Fwd IAT Mean                   0
 Fwd IAT Std                    0
 Fwd IAT Max                    0
 Fwd IAT Min                    0
Bwd IAT Total                   0
 Bwd IAT Mean                   0
 Bwd IAT Std                    0
 Bwd IAT Max                    0
 Bwd IAT Min                    0
Fwd PSH Flags                   0
 Bwd PSH Flags                  0
 Fwd URG Flags                  0
 Bwd URG Flags                  0
 Fwd Header Length              0
 Bwd Header Length              0
Fwd Packets/s                   0
 Bwd Packets/s                  0
 Min Packet Length              0
 Max Packet Length              0
 Packet Length Mean             0
 Packet Length Std              0
 Packet Length Variance         0
FIN Flag Count                  0
 SYN Flag Count                 0
 RST Flag Count                 0
 PSH Flag Count                 0
 ACK Flag Count                 0
 URG Flag Count                 0
 CWE Flag Count                 0
 ECE Flag Count                 0
 Down/Up Ratio                  0
 Average Packet Size            0
 Avg Fwd Segment Size           0
 Avg Bwd Segment Size           0
 Fwd Header Length.1            0
Fwd Avg Bytes/Bulk              0
 Fwd Avg Packets/Bulk           0
 Fwd Avg Bulk Rate              0
 Bwd Avg Bytes/Bulk             0
 Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
 Subflow Fwd Bytes              0
 Subflow Bwd Packets            0
 Subflow Bwd Bytes              0
Init_Win_bytes_forward          0
 Init_Win_bytes_backward        0
 act_data_pkt_fwd               0
 min_seg_size_forward           0
Active Mean                     0
 Active Std                     0
 Active Max                     0
 Active Min                     0
Idle Mean                       0
 Idle Std                       0
 Idle Max                       0
 Idle Min                       0
 Label                          0
dtype: int64

In [ ]:
Yt=labelencoder.transform(Yt)

In [ ]:
Xt.shape

(95124, 78)

In [ ]:
t=pd.DataFrame(Yt)

In [ ]:
t.head()

   0
0  4
1  5
2  0
3  4
4  9

In [ ]:
t.value_counts()

0
0     76483
4      7790
9      5253
2      4265
3       330
7       281
5       212
6       194
10      181
1        66
11       44
13       22
8         1
12        1
14        1
Name: count, dtype: int64

In [ ]:
t.loc[[1,11,13,12,8,14]]=0

In [ ]:
t.value_counts()

0
0     76484
4      7790
9      5253
2      4265
3       330
7       281
5       211
6       194
10      181
1        66
11       44
13       22
8         1
12        1
14        1
Name: count, dtype: int64

In [ ]:
t=t[t!=1]

In [ ]:
t=t[t!=8]

In [ ]:
t=t[t!=11]

In [ ]:
t=t[t!=12]

In [ ]:
t=t[t!=13]

In [ ]:
t=t[t!=14]

In [ ]:
t=labelencoder.fit_transform(t)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
Xt.shape

(95124, 78)

In [ ]:
Yt=t

In [ ]:
opt.fit(Xt,Yt)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [ ]:
Xt.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [ ]:
print(Xt)

None

In [ ]:
from sklearn.metrics import classification_report

# Predict on test data
Ypt= opt.predict(Xt)

# Generate report
report_new = classification_report(Yt,Ypt)

print(report_new)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     76484
           1       1.00      1.00      1.00      4265
           2       1.00      1.00      1.00       330
           3       1.00      1.00      1.00      7790
           4       1.00      1.00      1.00       211
           5       1.00      1.00      1.00       194
           6       1.00      1.00      1.00       281
           7       1.00      1.00      1.00      5253
           8       1.00      1.00      1.00       181
           9       1.00      0.99      1.00       135

    accuracy                           1.00     95124
   macro avg       1.00      1.00      1.00     95124
weighted avg       1.00      1.00      1.00     95124

In [ ]:
Yt=Yt[Yt!=8]

In [ ]:
Yt=Yt[Yt!=9]

In [ ]:
Yt=Yt[Yt!=13]

In [ ]:
g=Yt

In [ ]:
g=pd.DataFrame(Yt)

In [ ]:
g.head()

    0
0   4
1   5
2   0
3   4
4  10

In [ ]:
g=g[g!=8]

In [ ]:
g=g[g!=9]

In [ ]:
g=g[g!=13]

In [ ]:
g=labelencoder.fit_transform(g)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
h=pd.DataFrame(g)

In [ ]:
h.value_counts()

0
0     411203
4      41801
8      28751
2      23160
3       1861
7       1436
9       1067
6       1048
5        994
1        355
10       272
11       117
Name: count, dtype: int64

In [ ]:
Yt=h.to_numpy()

In [ ]:
Yt

array([[4],
       [5],
       [0],
       ...,
       [4],
       [4],
       [0]])

In [ ]:
h=labelencoder.fit_transform(h)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
h.shape

(512065,)

In [ ]:
Xt.shape

(512077, 78)

In [ ]:
Yt.shape

(512065,)

In [ ]:
Yt=h

In [ ]:
Yt.shape

(512065,)

In [ ]:
Xt.shape

(512077, 78)

In [ ]:
Yt.shape

(512065,)

In [ ]:
from imblearn.over_sampling import SMOTE
from collections import Counter
smote = SMOTE(random_state=2)

In [ ]:
Counter(Yt)

Counter({np.int64(4): 41801,
         np.int64(5): 994,
         np.int64(0): 411203,
         np.int64(8): 28751,
         np.int64(7): 1436,
         np.int64(2): 23160,
         np.int64(10): 272,
         np.int64(3): 1861,
         np.int64(9): 1067,
         np.int64(1): 355,
         np.int64(6): 1048,
         np.int64(11): 117})

In [ ]:
Yt.shape

(512065,)

In [ ]:
Xt.shape

(512077, 78)

In [ ]:
h.shape

(512065,)

In [ ]:
q=pd.DataFrame(Yt)

In [ ]:
q.value_counts()

0
0     411203
4      41801
10     28751
2      23160
3       1861
7       1436
11      1067
6       1048
5        994
1        355
12       272
14       117
9          6
13         4
8          2
Name: count, dtype: int64

In [ ]:
q=q[q!=8]

In [ ]:
q=q[q!=9]

In [ ]:
q=q[q!=13]

In [ ]:
q=labelencoder.fit_transform(q)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
Yt=q

In [ ]:
Yt.shape

(512077,)

In [ ]:
Xt.shape

(512077, 78)

In [ ]:
opt.fit(Xt,Yt)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [ ]:
Xt.columns

Index([' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min'],
      dtype='object')

In [ ]:
Xt=Xt.drop(columns=' Label',inplace=True)

In [ ]:
Xt.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,998,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,2004.008016,9.980000e+02,0.000000e+00,998,998,998,998.0,0.0,998,998,0,0.0,0.0,0,0,0,0,0,0,64,0,2004.008016,0.000000,0,0,0.0,0.000000,0.0,0,0,0,0,1,0,0,0,0,0.00,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,251,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0
1,63111103,7,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,0.110916,1.050000e+07,1.190000e+07,32100000,999612,63100000,10500000.0,11900000.0,32100000,999612,0,0.0,0.0,0,0,0,0,0,0,280,0,0.110916,0.000000,0,0,0.0,0.000000,0.0,0,0,0,1,0,0,0,0,0,0.00,0.0,0.0,280,0,0,0,0,0,0,7,0,0,0,29200,-1,0,40,7015565.0,0.0,7015565,7015565,18700000.0,12200000.0,32100000,8015910
2,202,2,2,98,130,49,49,49.0,0.0,65,65,65.0,0.0,1.128713e+06,19801.980200,6.733333e+01,3.348632e+01,106,48,48,48.0,0.0,48,48,48,48.0,0.0,48,48,0,0,0,0,40,40,9900.990099,9900.990099,49,65,55.4,8.763561,76.8,0,0,0,0,0,0,0,0,1,69.25,49.0,65.0,40,0,0,0,0,0,0,2,98,2,130,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0
3,3,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.000000e+00,666666.666700,3.000000e+00,0.000000e+00,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,64,0,666666.666700,0.000000,0,0,0.0,0.000000,0.0,0,0,0,0,1,0,0,0,0,0.00,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,274,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0
4,37,1,1,0,6,0,0,0.0,0.0,6,6,6.0,0.0,1.621622e+05,54054.054050,3.700000e+01,0.000000e+00,37,37,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,40,20,27027.027030,27027.027030,0,6,2.0,3.464102,12.0,0,0,0,1,0,0,0,0,1,3.00,0.0,6.0,40,0,0,0,0,0,0,1,0,1,6,29200,0,0,40,0.0,0.0,0,0,0.0,0.0,0,0

In [ ]:
Xt.shape

(512077, 77)

In [ ]:
Yt.shape

(512077,)

In [ ]:
opt.fit(Xt,Yt)

BayesSearchCV(cv=2,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=8, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=100, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})