<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day14_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import numpy as np

In [127]:
import pandas as pd

In [128]:
d=pd.concat([pd.read_csv('SDNFlow_Dataset_Normal.csv'),pd.read_csv('SDNFlow_Dataset_attack.csv')])

In [129]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [130]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [131]:
test=pd.read_csv('modified_concatenated_InSDN_DatasetCSV.csv')

In [132]:
test.head()

,Flow ID,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,10/1/2020 5:02,269709,4,5,48,23,30,0,12.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,10/1/2020 5:02,268599,2,3,0,23,0,0,0.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,10/1/2020 5:02,22194,5,5,53,30,30,0,10.6,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,10/1/2020 1:39,9556,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,10/1/2020 1:39,8782,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [133]:
d.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [134]:
d=d.drop(columns=['flow_ID','eth_type','ipv4_src','ipv4_dst','ip_proto','src_port','dst_port','Byts_max_interval_2s', 'Byts_min_interval_2s', 'Byts_mean_interval_2s', 'Byts_std_interval_2s',
    'Pkts_max_interval_2s', 'Pkts_mean_interval_2s', 'Pkts_min_interval_2s', 'Pkts_std_interval_2s',
    'TnBPDstIP', 'TnBPSrcIP', 'TnPPDstIP', 'TnPPSrcIP', 'TnPPerDport',
    'Tn_FlowsPDstIP', 'Tn_FlowsPSrcIP', 'Attack'])

In [135]:
d.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Category
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,SSH
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,SSH
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,ICMP
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,STREAMING
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,STREAMING

In [136]:
test.head()

,Flow ID,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,10/1/2020 5:02,269709,4,5,48,23,30,0,12.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,10/1/2020 5:02,268599,2,3,0,23,0,0,0.0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,10/1/2020 5:02,22194,5,5,53,30,30,0,10.6,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,10/1/2020 1:39,9556,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,10/1/2020 1:39,8782,4,4,30,30,30,0,7.5,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [137]:
test=test.drop(columns=['Flow ID','Timestamp','Fwd Pkt Len Max',	'Fwd Pkt Len Min',	'Fwd Pkt Len Mean',	'Fwd Pkt Len Std'	,'Bwd Pkt Len Max',	'Bwd Pkt Len Min'	,'Bwd Pkt Len Mean'	,'Bwd Pkt Len Std'])

In [138]:
test=test.drop(columns=['Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
    'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
    'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min',
    'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags',
    'Fwd Header Len', 'Bwd Header Len'])

In [139]:
test.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Flow Byts/s,Flow Pkts/s,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,263.246684,33.369298,14.830799,18.538499,0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,85.629507,18.615110,7.446044,11.169066,0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,3739.749482,450.572227,225.286113,225.286113,0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,6278.777731,837.170364,418.585182,418.585182,0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,6832.156684,910.954225,455.477112,455.477112,0,...,0,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [140]:
test=test.drop(columns=['Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min'])

In [141]:
test.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Flow Byts/s,Flow Pkts/s,Fwd Pkts/s,Bwd Pkts/s,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,269709,4,5,48,23,263.246684,33.369298,14.830799,18.538499,0.0,0.0,0,0,0.0,0.0,0,0,U2R
1,268599,2,3,0,23,85.629507,18.615110,7.446044,11.169066,0.0,0.0,0,0,0.0,0.0,0,0,U2R
2,22194,5,5,53,30,3739.749482,450.572227,225.286113,225.286113,0.0,0.0,0,0,0.0,0.0,0,0,U2R
3,9556,4,4,30,30,6278.777731,837.170364,418.585182,418.585182,0.0,0.0,0,0,0.0,0.0,0,0,BFA
4,8782,4,4,30,30,6832.156684,910.954225,455.477112,455.477112,0.0,0.0,0,0,0.0,0.0,0,0,BFA

In [142]:
test=test.drop(columns=['Fwd Pkts/s','Bwd Pkts/s'])

In [143]:
d.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Category
0,6.472,113472,628,17532.756490,97.033375,180.687898,12560,2,2.0,2,0.0,5,5.0,5,0.0,SSH
1,6.465,24492,370,3788.399072,57.231245,66.194595,7400,2,2.0,2,0.0,5,5.0,5,0.0,SSH
2,4.798,2211,4,460.817007,0.833681,552.750000,32,4,4.0,4,0.0,0,0.0,0,0.0,ICMP
3,595.270,10827817,25627,18189.757590,43.051052,422.515979,205016,596,596.0,596,0.0,0,0.0,0,0.0,STREAMING
4,595.251,154551644,114704,259641.132900,192.698542,1347.395418,917632,596,596.0,596,0.0,0,0.0,0,0.0,STREAMING

In [144]:
d=d.drop(columns=['fwd_header_len'])

In [145]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [146]:
le=LabelEncoder()

In [147]:
scaler=StandardScaler()

In [148]:
d['Category'].value_counts()

Category
HTTP                 164974
probe                151456
dos                  123807
ddos                  74644
password-guessing     67288
DNS                   53551
sql_injection         17787
u2r                    6282
STREAMING              1487
SSH                    1133
ICMP                    305
FTP                      91
NTP                      23
Name: count, dtype: int64

In [149]:
d.shape,test.shape

((662828, 15), (343889, 16))

In [150]:
d['Category'].str.upper().value_counts()

Category
HTTP                 164974
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
STREAMING              1487
SSH                    1133
ICMP                    305
FTP                      91
NTP                      23
Name: count, dtype: int64

In [151]:
d=d[~d['Category'].isin(['STREAMING','SSH','ICMP','FTP','NTP'])]

In [152]:
d['Category'].value_counts()

Category
HTTP                 164974
probe                151456
dos                  123807
ddos                  74644
password-guessing     67288
DNS                   53551
sql_injection         17787
u2r                    6282
Name: count, dtype: int64

In [153]:
d['Category']=d['Category'].str.upper()

In [154]:
d['Category'].value_counts()

Category
HTTP                 164974
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
Name: count, dtype: int64

In [155]:
d['Category']=d['Category'].rename({'PASSWORD-GUESSING':'BFA','DNS':'BOTNET','HTTP':'NORMAL'})

In [156]:
d['Category'].value_counts()

Category
HTTP                 164974
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
Name: count, dtype: int64

In [157]:
from imblearn.over_sampling import ADASYN

In [158]:
adasyn=ADASYN()

In [159]:
test['Label'].value_counts()

Label
Probe         98129
DDoS          73529
Normal        68424
DoS           53616
DDoS          48413
BFA            1405
Web-Attack      192
BOTNET          164
U2R              17
Name: count, dtype: int64

In [160]:
test['Label']=test['Label'].str.strip()

In [161]:
test['Label'].value_counts()

Label
DDoS          121942
Probe          98129
Normal         68424
DoS            53616
BFA             1405
Web-Attack       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [162]:
test['Label']=test['Label'].str.upper()

In [163]:
test['Label'].value_counts()

Label
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [164]:
d['Category']=d['Category'].rename({'HTTP':'NOMRAL','PASSWORD-GUESSING':'BFA','DNS':'BOTNET','SQL_INJECTION':'WEB-ATTACK'})

In [165]:
d['Category'].value_counts()

Category
HTTP                 164974
PROBE                151456
DOS                  123807
DDOS                  74644
PASSWORD-GUESSING     67288
DNS                   53551
SQL_INJECTION         17787
U2R                    6282
Name: count, dtype: int64

In [166]:
d.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Category
48,0.555,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,DNS
49,0.551,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,DNS
50,22.560,1799,11,79.742908,0.487589,163.545455,2,2.0,2,0.0,10,10.0,10,0.0,HTTP
52,22.413,4516,7,201.490207,0.312319,645.142857,2,2.0,2,0.0,10,10.0,10,0.0,HTTP
53,0.232,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,DNS

In [167]:
d['Category']=d['Category'].str.strip()

In [168]:
d['Category']=d['Category'].replace({'HTTP':'NORMAL','PASSWORD-GUESSING':'BFA','DNS':'BOTNET','SQL_INJECTION':'WEB-ATTACK'})

In [169]:
d['Category'].value_counts()

Category
NORMAL        164974
PROBE         151456
DOS           123807
DDOS           74644
BFA            67288
BOTNET         53551
WEB-ATTACK     17787
U2R             6282
Name: count, dtype: int64

In [170]:
d.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Category
48,0.555,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,BOTNET
49,0.551,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,BOTNET
50,22.560,1799,11,79.742908,0.487589,163.545455,2,2.0,2,0.0,10,10.0,10,0.0,NORMAL
52,22.413,4516,7,201.490207,0.312319,645.142857,2,2.0,2,0.0,10,10.0,10,0.0,NORMAL
53,0.232,0,0,0.000000,0.000000,0.000000,1,1.0,1,0.0,0,0.0,0,0.0,BOTNET

In [171]:
test['Label'].value_counts()

Label
DDOS          121942
PROBE          98129
NORMAL         68424
DOS            53616
BFA             1405
WEB-ATTACK       192
BOTNET           164
U2R               17
Name: count, dtype: int64

In [172]:
d['Category'].value_counts()

Category
NORMAL        164974
PROBE         151456
DOS           123807
DDOS           74644
BFA            67288
BOTNET         53551
WEB-ATTACK     17787
U2R             6282
Name: count, dtype: int64

In [173]:
d=d[~d['Category'].isin(['DDOS',"BOTNET"])]

In [174]:
d['Category']=le.fit_transform(d['Category'])

In [176]:
test=test[~test['Label'].isin(['DDOS',"BOTNET"])]

In [177]:
test['Label']=le.transform(test['Label'])

In [178]:
test['Label'].value_counts()

Label
3    98129
2    68424
1    53616
0     1405
5      192
4       17
Name: count, dtype: int64

In [179]:
d['Category'].value_counts()

Category
2    164974
3    151456
1    123807
0     67288
5     17787
4      6282
Name: count, dtype: int64

In [180]:
test.isnull().sum()

Flow Duration      0
Tot Fwd Pkts       0
Tot Bwd Pkts       0
TotLen Fwd Pkts    0
TotLen Bwd Pkts    0
Flow Byts/s        0
Flow Pkts/s        0
Active Mean        0
Active Std         0
Active Max         0
Active Min         0
Idle Mean          0
Idle Std           0
Idle Max           0
Idle Min           0
Label              0
dtype: int64

In [181]:
Y=d['Category']

In [182]:
X=d.drop(columns='Category')

In [183]:
X.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std
50,22.560,1799,11,79.742908,0.487589,163.545455,2,2.000000,2,0.000000,10,10.0,10,0.0
52,22.413,4516,7,201.490207,0.312319,645.142857,2,2.000000,2,0.000000,10,10.0,10,0.0
55,42.233,2522,13,59.716336,0.307816,194.000000,6,2.800000,2,1.600000,10,8.5,6,1.5
56,21.172,3029,6,143.066314,0.283393,504.833333,6,3.333333,2,1.885618,9,7.5,6,1.5
59,21.128,689,6,32.610754,0.283983,114.833333,2,2.000000,2,0.000000,9,8.5,8,0.5

In [184]:
Y.head()

50    2
52    2
55    2
56    2
59    2
Name: Category, dtype: int64

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [187]:
from sklearn.preprocessing import StandardScaler

In [188]:
scaler=StandardScaler()

In [189]:
X_train=scaler.fit_transform(X_train)

In [190]:
X_test=scaler.transform(X_test)

In [191]:
from imblearn.over_sampling import SMOTE;
smote=SMOTE();

In [192]:
Xoversampled,Yoversampled=smote.fit_resample(X_train,Y_train)

In [193]:
from xgboost import XGBClassifier


xgb=XGBClassifier()


estimators=[('xgb',xgb)]


from sklearn.pipeline import Pipeline


pipe=Pipeline(steps=estimators)


pipe

Pipeline(steps=[('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [194]:
from skopt import BayesSearchCV


from skopt.space import Real,Categorical,Integer


search_space = {
    'max_depth': Integer(3, 10),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(400, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=3,scoring='roc_auc',random_state=42)


opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=3
)

In [195]:
opt.fit(Xoversampled,Yoversampled)

BayesSearchCV(cv=3,
              estimator=XGBClassifier(base_score=None, booster=None,
                                      callbacks=None, colsample_bylevel=None,
                                      colsample_bynode=None,
                                      colsample_bytree=None, device=None,
                                      early_stopping_rounds=None,
                                      enable_categorical=False,
                                      eval_metric=None, feature_types=None,
                                      feature_weights=None, gamma=None,
                                      grow_policy=None, importance_type=None,
                                      interaction_constraints=No...
                             'max_depth': Integer(low=3, high=10, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=400, high=500, prior='uniform', transform='normalize'),
                             'reg_alpha': Real(low=0.0, high=5.0, prior='uniform', transform='normalize'),
                             'reg_lambda': Real(low=0.1, high=5.0, prior='uniform', transform='normalize'),
                             'subsample': Real(low=0.6, high=1.0, prior='uniform', transform='normalize')})

In [196]:
Ypred=opt.predict(Xoversampled)

In [197]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [198]:
accuracy_score(Yoversampled,Ypred)

0.8557995985912826

In [199]:
classification_report(Yoversampled,Ypred)

'              precision    recall  f1-score   support\n\n           0       0.96      0.80      0.88    132035\n           1       0.95      0.92      0.93    132035\n           2       0.93      0.70      0.80    132035\n           3       0.59      0.96      0.73    132035\n           4       0.97      0.90      0.93    132035\n           5       0.96      0.84      0.90    132035\n\n    accuracy                           0.86    792210\n   macro avg       0.89      0.86      0.86    792210\nweighted avg       0.89      0.86      0.86    792210\n'

In [200]:
confusion_matrix(Yoversampled,Ypred)

array([[106180,    896,   1757,  21455,    867,    880],
       [   752, 121686,   2333,   5384,    483,   1397],
       [  1619,   3250,  92184,  32626,   1340,   1016],
       [   430,   1235,   1981, 127401,    539,    449],
       [   453,    109,    336,  11704, 119110,    323],
       [   797,   1211,    684,  16842,   1089, 111412]])